In [2]:
import kagglehub

path = kagglehub.dataset_download(
    "irkaal/foodcom-recipes-and-reviews"
)

print("Path to dataset files:", path)

Path to dataset files: /Users/abbygoblick/.cache/kagglehub/datasets/irkaal/foodcom-recipes-and-reviews/versions/2

In [3]:
import os

os.listdir(path)

['reviews.csv', 'recipes.csv', 'recipes.parquet', 'reviews.parquet']

In [4]:
import pandas as pd
import os

recipes_path = os.path.join(path, "recipes.parquet")
reviews_path = os.path.join(path, "reviews.parquet")

recipes = pd.read_parquet(recipes_path)
reviews = pd.read_parquet(reviews_path)

In [5]:
print("Recipes:", recipes.shape)
print("Reviews:", reviews.shape)

Recipes: (522517, 28)
Reviews: (1401982, 8)

In [68]:
recipes.columns.tolist()

['RecipeId',
 'Name',
 'AuthorId',
 'AuthorName',
 'CookTime',
 'PrepTime',
 'TotalTime',
 'DatePublished',
 'Description',
 'Images',
 'RecipeCategory',
 'Keywords',
 'RecipeIngredientQuantities',
 'RecipeIngredientParts',
 'AggregatedRating',
 'ReviewCount',
 'Calories',
 'FatContent',
 'SaturatedFatContent',
 'CholesterolContent',
 'SodiumContent',
 'CarbohydrateContent',
 'FiberContent',
 'SugarContent',
 'ProteinContent',
 'RecipeServings',
 'RecipeYield',
 'RecipeInstructions']

In [7]:
reviews.columns.tolist()

['ReviewId',
 'RecipeId',
 'AuthorId',
 'AuthorName',
 'Rating',
 'Review',
 'DateSubmitted',
 'DateModified']

In [8]:
recipes.head()

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38.0,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09 21:46:00+00:00,Make and share this Low-Fat Berry Blue Frozen ...,[https://img.sndimg.com/food/image/upload/w_55...,...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"[Toss 2 cups berries with sugar., Let stand fo..."
1,39.0,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29 13:12:00+00:00,Make and share this Biryani recipe from Food.com.,[https://img.sndimg.com/food/image/upload/w_55...,...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,[Soak saffron in warm milk for 5 minutes and p...
2,40.0,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05 19:52:00+00:00,This is from one of my first Good House Keepi...,[https://img.sndimg.com/food/image/upload/w_55...,...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"[Into a 1 quart Jar with tight fitting lid, pu..."
3,41.0,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03 14:54:00+00:00,This dish is best prepared a day in advance to...,[https://img.sndimg.com/food/image/upload/w_55...,...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"[Drain the tofu, carefully squeezing out exces..."
4,42.0,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19 06:19:00+00:00,Make and share this Cabbage Soup recipe from F...,[https://img.sndimg.com/food/image/upload/w_55...,...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"[Mix everything together and bring to a boil.,..."

In [9]:
reviews.head()

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25 21:44:00+00:00,2000-01-25 21:44:00+00:00
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17 16:49:59+00:00,2001-10-17 16:49:59+00:00
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25 09:00:00+00:00,2000-02-25 09:00:00+00:00
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13 21:15:00+00:00,2000-03-13 21:15:00+00:00
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28 12:51:00+00:00,2000-03-28 12:51:00+00:00

In [10]:
print("Recipes:", recipes.shape)
print("Reviews:", reviews.shape)

Recipes: (522517, 28)
Reviews: (1401982, 8)

In [13]:
choc_chip_candidates = recipes[
    recipes["Name"].str.contains(
        "chocolate chip cookie",
        case=False,
        na=False
    )
].copy()

print("Candidates:", len(choc_chip_candidates))

Candidates: 1775

In [14]:
choc_chip_candidates[
    ["RecipeId", "Name", "RecipeCategory", "ReviewCount", "AggregatedRating"]
].head(50)

,RecipeId,Name,RecipeCategory,ReviewCount,AggregatedRating
168,218.0,Chocolate Chip Cookie Pizza,Dessert,NaN,NaN
1828,3307.0,Mrs. Fields Chocolate Chip Cookies,Drop Cookies,8.0,2.5
2109,3599.0,Best Basic Chocolate Chip Cookies,Drop Cookies,12.0,4.5
2415,3953.0,Oatmeal Chocolate Chip Cookies,Drop Cookies,19.0,5.0
2416,3954.0,Oatmeal Chocolate Chip Cookies (No Eggs),Drop Cookies,89.0,5.0
2487,4044.0,Ambrosia Oatmeal Chocolate Chip Cookies,Drop Cookies,7.0,3.5
2488,4045.0,Clementine's Oatmeal Chocolate Chip Cookies,Drop Cookies,8.0,4.5
2492,4050.0,Canadian Living's Best Chocolate Chip Cookies,Drop Cookies,85.0,5.0
2493,4051.0,Mike's Grand Marnier Chocolate Chip Cookies,Drop Cookies,2.0,4.0
2507,4065.0,Oatmeal Chocolate Chip Cookies II,Drop Cookies,68.0,5.0
2529,4092.0,Chocolate Chip Cookies,Drop Cookies,8.0,5.0
3725,6482.0,Decadent Chocolate Chip Cookies,Dessert,31.0,4.5
5508,8477.0,Pistachio White Chocolate Chip Cookies,Drop Cookies,2.0,5.0
6902,10022.0,Crispy Chewy Chocolate Chip Cookies,Dessert,15.0,4.0
6997,10117.0,Best Ever Chocolate Chip Cookies,Drop Cookies,68.0,5.0
7004,10125.0,Soft Batch Chocolate Chip Cookies,Drop Cookies,243.0,5.0
7167,10289.0,The Ultimate Chocolate Chip Cookies!,Drop Cookies,2.0,4.5
7305,10429.0,Chocolate Chip Cookies,Drop Cookies,8.0,5.0
8872,12026.0,Chocolate Chip Cookies (Grandma's From-Scratch...,Drop Cookies,23.0,5.0
10122,13307.0,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,Dessert,156.0,5.0
10471,13661.0,Ghirardelli' S Ultimate Chocolate Chip Cookies,Drop Cookies,62.0,5.0
10709,13902.0,Rich chocolate chip cookies,Dessert,1.0,3.0
10719,13913.0,My Family's Favorite Chocolate Chip Cookies,Drop Cookies,NaN,NaN
11285,14490.0,Chocolate Chip Cookies in a Bag!,Drop Cookies,NaN,NaN
12153,15376.0,Decadent Chocolate Chip Cookies for Kisses,Drop Cookies,5.0,5.0
12201,15426.0,Easy chocolate chip cookies,Drop Cookies,17.0,5.0
12436,15668.0,Chocolate-Orange-Chocolate Chip Cookies,Dessert,39.0,5.0
12525,15759.0,Chewy Chocolate Chip Cookies,Drop Cookies,5.0,4.5
13085,16341.0,PB oatmeal chocolate chip cookies,Drop Cookies,2.0,3.0
13180,16437.0,Annette Funicello's Peanut Butter Chocolate Ch...,Drop Cookies,3.0,4.5
13842,17113.0,Chewy Delicious Chocolate Chip Cookies,Drop Cookies,66.0,4.5
13987,17262.0,Slice &amp; Bake Chocolate Chip Cookies,Dessert,8.0,5.0
14104,17383.0,Caramel Lace Chocolate Chip Cookies,Drop Cookies,5.0,4.0
14223,17506.0,Best Chocolate Chip Cookies,Drop Cookies,14.0,5.0
14234,17517.0,Great Chocolate Chip Cookies,Drop Cookies,3.0,5.0
14365,17651.0,Triple Chocolate Chip Cookies,Drop Cookies,16.0,5.0
15209,18518.0,Ultimate Chocolate Chip Cookies,Drop Cookies,2.0,4.0
15934,19260.0,Black & White Chocolate Chip Cookies,Drop Cookies,17.0,5.0
16053,19379.0,Sour Cream Chocolate Chip Cookies,Quick Breads,37.0,5.0
16742,20075.0,Chocolate Chip Cookie Turtle,Bar Cookie,2.0,5.0
17068,20408.0,Soft Chocolate Chip Cookies,Drop Cookies,509.0,5.0
17280,20629.0,Grandma's Chocolate Chip Cookies,Drop Cookies,10.0,5.0
17412,20763.0,Double Chocolate Chip Cookies,Drop Cookies,35.0,5.0
17530,20884.0,CHEWY Chocolate Chip Cookies,Drop Cookies,18.0,4.5
17892,21248.0,Chocolate Chip Cookies,Dessert,26.0,5.0
18066,21425.0,Chocolate Chocolate Chip Cookies,Drop Cookies,15.0,4.5
19370,22765.0,Katie's Chocolate Chip Cookies,Drop Cookies,13.0,5.0
19697,23096.0,Annie Glenn's Chocolate Chip Cookies,Drop Cookies,2.0,5.0
19853,23255.0,Passover Chocolate Chip Cookies,Dessert,5.0,5.0
20084,23494.0,Giant Peanut Butter Oatmeal Chocolate Chip Coo...,Drop Cookies,3.0,4.5

In [15]:
choc_chip_candidates["RecipeCategory"].value_counts().head(30)

RecipeCategory
Drop Cookies              826
Dessert                   680
Chocolate Chip Cookies    144
Bar Cookie                 36
< 30 Mins                  13
Frozen Desserts            11
Cheesecake                  9
Pie                         8
Breakfast                   8
Candy                       6
Nuts                        4
< 60 Mins                   4
Quick Breads                3
Sweet                       3
Beverages                   2
Grains                      2
Ice Cream                   2
High Protein                2
Lunch/Snacks                1
Tarts                       1
Fruit                       1
Free Of...                  1
Peanut Butter               1
Kid Friendly                1
Canadian                    1
Toddler Friendly            1
Beans                       1
Shakes                      1
Breads                      1
< 15 Mins                   1
Name: count, dtype: int64

In [16]:
print("Total title candidates:", len(choc_chip_candidates))

Total title candidates: 1775

In [17]:
cookie_categories = [
    "Chocolate Chip Cookies",
    "Drop Cookies",
    "Dessert"
]

likely_cookies = choc_chip_candidates[
    choc_chip_candidates["RecipeCategory"].isin(cookie_categories)
].copy()

print("Likely cookie recipes:", len(likely_cookies))

Likely cookie recipes: 1650

In [18]:
high_confidence = choc_chip_candidates[
    choc_chip_candidates["RecipeCategory"] == "Chocolate Chip Cookies"
].copy()

drop_cookies = choc_chip_candidates[
    choc_chip_candidates["RecipeCategory"] == "Drop Cookies"
].copy()

other_candidates = choc_chip_candidates[
    ~choc_chip_candidates["RecipeCategory"].isin(
        ["Chocolate Chip Cookies", "Drop Cookies"]
    )
].copy()

print("Chocolate Chip Cookies category:", len(high_confidence))
print("Drop Cookies category:", len(drop_cookies))
print("Everything else:", len(other_candidates))
print("Total:", len(choc_chip_candidates))

Chocolate Chip Cookies category: 144
Drop Cookies category: 826
Everything else: 805
Total: 1775

In [19]:
choc_chip_candidates[
    [
        "RecipeId",
        "Name",
        "RecipeCategory",
        "ReviewCount",
        "AggregatedRating"
    ]
].sort_values(
    "ReviewCount",
    ascending=False
).head(50)

,RecipeId,Name,RecipeCategory,ReviewCount,AggregatedRating
17068,20408.0,Soft Chocolate Chip Cookies,Drop Cookies,509.0,5.0
75588,80470.0,Bakery Style Chewy Chocolate Chip Cookies,Drop Cookies,313.0,4.5
7004,10125.0,Soft Batch Chocolate Chip Cookies,Drop Cookies,243.0,5.0
95298,100727.0,"Thick, Soft, and Chewy Chocolate Chip Cookies",Drop Cookies,229.0,5.0
23372,26849.0,World's Best Chocolate Chip Cookies,Dessert,222.0,4.5
49241,53301.0,Chewy Double Chocolate Chip Cookies,Drop Cookies,221.0,5.0
47086,51104.0,Peanut Butter Chocolate Chip Cookies,Drop Cookies,186.0,5.0
34363,38041.0,My Favorite Chocolate Chip Cookies,Drop Cookies,186.0,5.0
95606,101041.0,Lisa's Swirled Chocolate Chip Cookies,Drop Cookies,183.0,5.0
111425,117317.0,Blue Ridge Mountains Chocolate Chip Cookies,Drop Cookies,168.0,5.0
10122,13307.0,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,Dessert,156.0,5.0
44402,48356.0,Soft and Chewy Chocolate Chip Cookies,Drop Cookies,117.0,5.0
2416,3954.0,Oatmeal Chocolate Chip Cookies (No Eggs),Drop Cookies,89.0,5.0
2492,4050.0,Canadian Living's Best Chocolate Chip Cookies,Drop Cookies,85.0,5.0
93717,99094.0,Chewy Vegan Chocolate Chocolate Chip Cookies,Dessert,80.0,5.0
71691,76416.0,Chocolate Chip Cookies,Drop Cookies,75.0,5.0
231526,241166.0,Yummy Oatmeal Chocolate Chip Cookies,Drop Cookies,74.0,5.0
2507,4065.0,Oatmeal Chocolate Chip Cookies II,Drop Cookies,68.0,5.0
6997,10117.0,Best Ever Chocolate Chip Cookies,Drop Cookies,68.0,5.0
13842,17113.0,Chewy Delicious Chocolate Chip Cookies,Drop Cookies,66.0,4.5
107859,113637.0,Pumpkin Chocolate Chip Cookies,Chocolate Chip Cookies,65.0,5.0
10471,13661.0,Ghirardelli' S Ultimate Chocolate Chip Cookies,Drop Cookies,62.0,5.0
224371,233825.0,Chocolate Chip Cookie Cake,Dessert,56.0,5.0
27019,30565.0,Oh My D-Lux Chocolate Chip Cookies,Drop Cookies,49.0,5.0
115658,121714.0,Gluten Free Awesome Chocolate Chip Cookies,Dessert,48.0,5.0
112549,118487.0,Thick and Chewy Chocolate Chip Cookies,Chocolate Chip Cookies,48.0,5.0
232424,242083.0,Low Fat Oatmeal Chocolate Chip Cookies,Dessert,45.0,5.0
134012,140679.0,Oatmeal Peanut Butter Chocolate Chip Cookies,Dessert,45.0,5.0
93935,99319.0,Clementine's Oatmeal Chocolate Chip Cookies,Drop Cookies,43.0,5.0
20730,24153.0,Easy Peanut Butter &amp; Chocolate Chip Cookies,Drop Cookies,43.0,5.0
164094,171792.0,Chocolate Chip Cookie Dough Dip,Dessert,42.0,5.0
53166,57336.0,Julie's Chocolate Chip Cookies,Drop Cookies,41.0,5.0
92770,98127.0,"Safe to Eat Raw Chocolate Chip Cookie ""dough""",Dessert,39.0,4.5
12436,15668.0,Chocolate-Orange-Chocolate Chip Cookies,Dessert,39.0,5.0
35028,38730.0,Ultimate Chocolate Chip Cookies,Drop Cookies,38.0,5.0
16053,19379.0,Sour Cream Chocolate Chip Cookies,Quick Breads,37.0,5.0
93805,99184.0,Bare Pantry Chocolate Chip Cookie Bars,Bar Cookie,37.0,4.5
145736,152834.0,Mint Chocolate Chip Cookies,Drop Cookies,37.0,5.0
54713,58919.0,Eggless Chocolate Chip Cookies,Dessert,36.0,4.5
17412,20763.0,Double Chocolate Chip Cookies,Drop Cookies,35.0,5.0
284633,295797.0,Brownie Mix Double Chocolate Chip Cookies,Dessert,34.0,5.0
325404,337714.0,Kittencal's Jumbo Chewy Bakery-Style Chocolate...,Drop Cookies,34.0,5.0
214469,223660.0,Ghirardelli Chocolate Chip Cookie Bar,Bar Cookie,34.0,5.0
27288,30843.0,Orange Cream Cheese Chocolate Chip Cookies,Drop Cookies,33.0,5.0
73548,78350.0,Pudding Chocolate Chip Cookies,Drop Cookies,33.0,5.0
61175,65563.0,Best Peanut Butter Chocolate Chip Cookies,Drop Cookies,32.0,5.0
3725,6482.0,Decadent Chocolate Chip Cookies,Dessert,31.0,4.5
220187,229517.0,Irresistible Chewy White Chocolate Chip Cookies,Dessert,31.0,5.0
188091,196504.0,Oatmeal Raisin Walnut Chocolate Chip Cookies,Drop Cookies,31.0,4.5
162381,170036.0,Heavenly Banana Oatmeal Chocolate Chip Cookies,Drop Cookies,30.0,5.0

In [20]:
exclude_terms = [
    "oatmeal",
    "peanut butter",
    "pumpkin",
    "banana",
    "bar",
    "cookie cake",
    "cookie pizza",
    "cookie dough",
    "raw",
    "gluten free",
    "gluten-free",
    "vegan",
    "eggless",
    "no eggs",
    "passover",
    "brownie",
    "white chocolate",
    "mint",
    "pudding",
    "cream cheese",
    "orange",
    "sour cream"
]

In [21]:
name_lower = choc_chip_candidates["Name"].str.lower()

exclude_mask = False

for term in exclude_terms:
    exclude_mask = exclude_mask | name_lower.str.contains(
        term,
        regex=False,
        na=False
    )

classic_candidates = choc_chip_candidates[
    ~exclude_mask
].copy()

print("Before filtering:", len(choc_chip_candidates))
print("After filtering:", len(classic_candidates))

Before filtering: 1775
After filtering: 1258

In [22]:
classic_candidates[
    [
        "RecipeId",
        "Name",
        "RecipeCategory",
        "ReviewCount",
        "AggregatedRating"
    ]
].sort_values(
    "ReviewCount",
    ascending=False
).head(50)

,RecipeId,Name,RecipeCategory,ReviewCount,AggregatedRating
17068,20408.0,Soft Chocolate Chip Cookies,Drop Cookies,509.0,5.0
75588,80470.0,Bakery Style Chewy Chocolate Chip Cookies,Drop Cookies,313.0,4.5
7004,10125.0,Soft Batch Chocolate Chip Cookies,Drop Cookies,243.0,5.0
95298,100727.0,"Thick, Soft, and Chewy Chocolate Chip Cookies",Drop Cookies,229.0,5.0
23372,26849.0,World's Best Chocolate Chip Cookies,Dessert,222.0,4.5
49241,53301.0,Chewy Double Chocolate Chip Cookies,Drop Cookies,221.0,5.0
34363,38041.0,My Favorite Chocolate Chip Cookies,Drop Cookies,186.0,5.0
95606,101041.0,Lisa's Swirled Chocolate Chip Cookies,Drop Cookies,183.0,5.0
111425,117317.0,Blue Ridge Mountains Chocolate Chip Cookies,Drop Cookies,168.0,5.0
10122,13307.0,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,Dessert,156.0,5.0
44402,48356.0,Soft and Chewy Chocolate Chip Cookies,Drop Cookies,117.0,5.0
2492,4050.0,Canadian Living's Best Chocolate Chip Cookies,Drop Cookies,85.0,5.0
71691,76416.0,Chocolate Chip Cookies,Drop Cookies,75.0,5.0
6997,10117.0,Best Ever Chocolate Chip Cookies,Drop Cookies,68.0,5.0
13842,17113.0,Chewy Delicious Chocolate Chip Cookies,Drop Cookies,66.0,4.5
10471,13661.0,Ghirardelli' S Ultimate Chocolate Chip Cookies,Drop Cookies,62.0,5.0
27019,30565.0,Oh My D-Lux Chocolate Chip Cookies,Drop Cookies,49.0,5.0
112549,118487.0,Thick and Chewy Chocolate Chip Cookies,Chocolate Chip Cookies,48.0,5.0
53166,57336.0,Julie's Chocolate Chip Cookies,Drop Cookies,41.0,5.0
35028,38730.0,Ultimate Chocolate Chip Cookies,Drop Cookies,38.0,5.0
17412,20763.0,Double Chocolate Chip Cookies,Drop Cookies,35.0,5.0
325404,337714.0,Kittencal's Jumbo Chewy Bakery-Style Chocolate...,Drop Cookies,34.0,5.0
3725,6482.0,Decadent Chocolate Chip Cookies,Dessert,31.0,4.5
123538,129896.0,Totally Chocolate Chocolate Chip Cookies,Drop Cookies,30.0,5.0
75954,80852.0,Low Sugar Chocolate Chip Cookies,Drop Cookies,29.0,5.0
166571,174356.0,Mrs. Fields Chocolate Chip Cookies,Dessert,29.0,5.0
140988,147910.0,Tate's Bake Shop Chocolate Chip Cookies,Dessert,28.0,4.5
288166,299433.0,Nestle Toll House Chocolate Chip Cookies (High...,Drop Cookies,28.0,4.5
78784,83777.0,Authentic Mrs. Fields Chocolate Chip Cookies,Drop Cookies,28.0,4.5
62638,67068.0,Delicious Soft Chocolate Chip Cookies,Drop Cookies,27.0,5.0
70955,75658.0,Otis Spunkmeyer's Chocolate Chip Cookies,Drop Cookies,27.0,4.0
17892,21248.0,Chocolate Chip Cookies,Dessert,26.0,5.0
47625,51655.0,Mean Chocolate Chip Cookies,Drop Cookies,26.0,5.0
461358,478379.0,Butter-Less Chocolate Chip Cookies,Chocolate Chip Cookies,26.0,5.0
108836,114638.0,Toasted Coconut Chocolate Chip Cookies,Dessert,25.0,5.0
36132,39852.0,The Best Chocolate Chip Cookies,Drop Cookies,25.0,5.0
8872,12026.0,Chocolate Chip Cookies (Grandma's From-Scratch...,Drop Cookies,23.0,5.0
365481,378778.0,Chocolate Chip Cookies - Betty Crocker's 1969 ...,Drop Cookies,23.0,5.0
26200,29734.0,Chocolate chip cookies,Drop Cookies,23.0,5.0
192166,200694.0,Whole Wheat Chocolate Chip Cookies,Drop Cookies,22.0,5.0
179084,187227.0,Low-Fat Double Chocolate Chip Cookies,Drop Cookies,22.0,5.0
135305,142029.0,Big and Chewy Chocolate Chip Cookies,Dessert,22.0,5.0
186845,195237.0,Award Winning Soft Chocolate Chip Cookies,Dessert,21.0,5.0
297754,309333.0,Chocolate Chip Cookie Cupcakes,Dessert,21.0,5.0
104217,109891.0,Chewy Secret Chocolate Chip Cookies,Dessert,20.0,4.5
248805,258922.0,Extraordinary Chocolate Chip Cookies,Drop Cookies,18.0,5.0
17530,20884.0,CHEWY Chocolate Chip Cookies,Drop Cookies,18.0,4.5
182206,190476.0,No Fuss Chewy Chocolate Chip Cookies,Dessert,18.0,4.0
53710,57889.0,The Best Chocolate Chip Cookies,Drop Cookies,17.0,5.0
427196,443024.0,Kitchenaid Chocolate Chip Cookies,Dessert,17.0,5.0

In [24]:
classic_ids = classic_candidates["RecipeId"]

classic_reviews = reviews[
    reviews["RecipeId"].isin(classic_ids)
].copy()

print("Classic cookie recipes:", len(classic_candidates))
print("Associated reviews:", len(classic_reviews))

Classic cookie recipes: 1258
Associated reviews: 5651

In [25]:
review_counts = (
    classic_reviews
    .groupby("RecipeId")
    .size()
    .rename("actual_review_count")
)

classic_with_review_counts = classic_candidates.merge(
    review_counts,
    on="RecipeId",
    how="left"
)

classic_with_review_counts["actual_review_count"] = (
    classic_with_review_counts["actual_review_count"]
    .fillna(0)
    .astype(int)
)

classic_with_review_counts[
    ["Name", "ReviewCount", "actual_review_count"]
].sort_values(
    "actual_review_count",
    ascending=False
).head(20)

,Name,ReviewCount,actual_review_count
28,Soft Chocolate Chip Cookies,509.0,488
118,Bakery Style Chewy Chocolate Chip Cookies,313.0,294
8,Soft Batch Chocolate Chip Cookies,243.0,233
163,"Thick, Soft, and Chewy Chocolate Chip Cookies",229.0,221
39,World's Best Chocolate Chip Cookies,222.0,216
76,Chewy Double Chocolate Chip Cookies,221.0,214
53,My Favorite Chocolate Chip Cookies,186.0,182
165,Lisa's Swirled Chocolate Chip Cookies,183.0,171
201,Blue Ridge Mountains Chocolate Chip Cookies,168.0,162
12,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,156.0,148
68,Soft and Chewy Chocolate Chip Cookies,117.0,113
2,Canadian Living's Best Chocolate Chip Cookies,85.0,82
114,Chocolate Chip Cookies,75.0,71
20,Chewy Delicious Chocolate Chip Cookies,66.0,64
7,Best Ever Chocolate Chip Cookies,68.0,62
13,Ghirardelli' S Ultimate Chocolate Chip Cookies,62.0,60
43,Oh My D-Lux Chocolate Chip Cookies,49.0,48
202,Thick and Chewy Chocolate Chip Cookies,48.0,46
82,Julie's Chocolate Chip Cookies,41.0,41
54,Ultimate Chocolate Chip Cookies,38.0,36

In [26]:
phenotype_terms = [
    "chewy",
    "chewier",
    "crispy",
    "crisp",
    "crunchy",
    "soft",
    "gooey",
    "cakey",
    "cake-like",
    "thick",
    "thin",
    "flat",
    "spread",
    "spreading",
    "dry",
    "moist",
    "dense"
]

for term in phenotype_terms:

    mask = (
        classic_reviews["Review"]
        .fillna("")
        .str.contains(
            term,
            case=False,
            regex=False
        )
    )

    n_reviews = mask.sum()

    n_recipes = (
        classic_reviews
        .loc[mask, "RecipeId"]
        .nunique()
    )

    print(
        f"{term:12} "
        f"reviews={n_reviews:5,} | "
        f"recipes={n_recipes:4,}"
    )

chewy        reviews=  869 | recipes= 220
chewier      reviews=   22 | recipes=  16
crispy       reviews=  240 | recipes= 116
crisp        reviews=  420 | recipes= 173
crunchy      reviews=  144 | recipes=  64
soft         reviews=  921 | recipes= 221
gooey        reviews=   79 | recipes=  41
cakey        reviews=   70 | recipes=  39
cake-like    reviews=   25 | recipes=  19
thick        reviews=  195 | recipes=  68
thin         reviews=1,084 | recipes= 286
flat         reviews=  402 | recipes= 140
spread       reviews=  224 | recipes= 106
spreading    reviews=   25 | recipes=  23
dry          reviews=  187 | recipes=  79
moist        reviews=  173 | recipes=  77
dense        reviews=   27 | recipes=  18

In [27]:
print("Recipes:", len(classic_candidates))
print("Reviews:", len(classic_reviews))
print(
    "Recipes with at least one review:",
    classic_reviews["RecipeId"].nunique()
)

Recipes: 1258
Reviews: 5651
Recipes with at least one review: 631

In [28]:
def sample_trait_reviews(trait, n=20):
    matches = classic_reviews[
        classic_reviews["Review"]
        .fillna("")
        .str.contains(
            trait,
            case=False,
            regex=False
        )
    ]

    print(f"Reviews containing '{trait}': {len(matches)}")

    return matches[
        ["RecipeId", "Rating", "Review"]
    ].sample(
        min(n, len(matches)),
        random_state=42
    )

In [29]:
sample_trait_reviews("chewy", 20)

Reviews containing 'chewy': 869

         RecipeId  Rating                                             Review
695333      80470       5  These cookies are awesome! Very dense, slightl...
134905     100727       5  Excellent! The very concise instructions were ...
882976      38041       5  These cookies are amazing! I am currently tryi...
135044      10289       4  These were very good--thick and crispy on the ...
1371249     48356       1  Um they are very cake like, not soft and chewy...
1244900     57336       5  I have tried MANY cookie recipes (including a ...
159859      76416       5     Loved 'em, simple as that.  Wonderfully chewy.
1299876     53301       5  WOW. These are delicious! They are exactly wha...
1033024     67068       5  Great recipe!  I am weird about using less tha...
841577      10117       5  My daughter wanted to make chocolate chip cook...
511931      13661       5  Absolutely delicious cookies! They disappeared...
753063      20408       5  Excellent! I can't believe how chewy these coo...
596895     100727       5  This is a very good choc. chip cookie.  Very s...
516310     250599       4  I've been looking for a recipe to make cookies...
857492     173707       5  I've been looking for the perfect chocolate ch...
380458      47194       5  These are perfection and my standard for choco...
755964     107231       5  These cookies are awesome!  So soft and chewy....
1393779     53301       5  These came out chewy and perfect. Mine didn’t ...
525821     251162       4  These are very good - don't expect a tradition...
947878     100727       5  Wow! I searched through the recipe sifter beca...

In [30]:
pd.set_option("display.max_colwidth", None)

In [31]:
sample_trait_reviews("soft", 20)

Reviews containing 'soft': 921

,RecipeId,Rating,Review
567222,287336,5,"Delicious cookies! I have made these twice now. The first time I made them for my family and the second time I made them for work. Both my family and my co-workers enjoyed them. My cookies were soft, yet the rice krispies gave them a crunch that we all loved Thank you for posting this winning recipe! (Made for PAC - Spring 2008)"
654800,20408,5,"Oh boy these cookies are TERRIFIC!! I left out the almond extract and used butterscotch pudding. So good, soft and rich, they cooked up perfectly in the 12 minutes. I got 4 dozen good-sized cookies from my batch of dough. I will definitely use this recipe again - thanks for sharing it! Made for Fall PAC 2008"
893129,80470,3,These cookies were beautiful! BUT the flavor was not what I hoped. Too sweet for me. They were not soft and chewy but I did not cool them on the baking sheet so that might be the reason. I have no problem with crunchy cookies if the flavor is good. Like one reviewer said the flavor of the dough was not so great. I love cookie dough but this was not flavorful at all. I wish I had been advised that after baking they would not be golden brown because I probably over baked them looking for a golden color. If these had Toll House/Mrs. Field's flavor to go with the look they would have been a keeper. But unfortunately I can't say I will try again. 3 stars for the look and an ok flavor.
527566,250362,5,"I found my forever choc chip cookie recipe with this one. I am just not gifted in the baking department. I have tried many cookie recipes here and thankfully have always made out but not like I have with this one. I made subs too so having said that I thought for sure they wouldnt turn out. I used all organic ingredients; and used whole wheat flour instead of white. Used sugar in the raw (turbinado?) for the sugar. I left the cookies plain, then after they were spooned onto the cookie sheet i added carob chips in some, walnuts in others, organic dark chocolate chunks in others and some left plain. My 4yr old daughter, who helped to make them loved them too. Texture was great; chewey and soft and the flavor was right on as well; very very fresh tasting. Marney you were right; I wont be going back to another chocolate chip cookie again. Thank you so much for sharing this."
890319,20408,5,"I have made these several times and forgot to rate this recipe. It has always come out soft, chewy, and declicious no matter what kind of pudding I use. I have used chocolate fudge, regular chocolate, vanilla, and banana cream. Thanks Peach :)"
141941,57889,5,"My search has ended!! Thank you so much, luvfood. Chocolate chip is my husband's favorite. For the last 7 years I have tried to find a recipe for choc. chip cookies that stay soft, but don't spread out thin. This is it! These are just wonderful. Followed the recipe exactly. Mine took 11-12 minutes on cookie sheets."
842465,331287,5,"Wow! I made these cookies on vacation and my family devoured all 48 cookies in less than 24 hours! They raved that these were the best cookies ever! Very soft, moist, and full of chocolate chips. Wonderful recipe!"
1105875,20408,0,"I really liked these cookies. We do not eat a lot of cookies here so I made one batch, baked half of them then froze the other half in 'pucks' for cooking later. They stay soft and there is so many different things you can put in the cookies. Can't wait to try with different flavored pudding."
1244871,10125,5,"These are just perfect, perfectly soft that is. The pudding is the secret ingredient and somehow makes it so that the cookies stay soft until they are all gone. I keep pudding on hand just so my husband can make these cookies."
71664,67068,5,"Finally! A soft chocolate chip cookie that's really soft! This recipe truly lives up to it's name. It's Delicious and Soft! I did use margerine instead of butter, and chocolate chips instead of chunks, and made smaller cookies so ended up with 3 1/2 dozen. The only mistake I made was not doubling the recipe! Thank you LuuvBunny for posting this wonderful recipe."
369418,54615,5,This is now my favorite cookie recipe! It is hard to find a good soft cookie recipe.
1365000,100727,4,These cookies were really good but following the directions they were huge. I guess 2 tablespoons is a lot per cookie. I also used 1/2 regular sugar and 1/2 brown sugar and I think they turned out really well. I think the secret is the shortening. That's how my grandma used to make her cookies but I've never tried it. Definitely makes a much softer and fluffier cookie. Will be making these again for sure.
972817,4050,5,"Can I add more stars to this review? These cookies perfect! Soft, thick, chewy. I can't keep them in the cookie jar and they're the most requested treat at work."
1001086,20408,5,"This is the recipe I have been looking for. Great flavor and these cookies stay soft. The only change I made was half butter, half margarine instead of the shortening. My husband loves these cookies and so do I. Thanks for a terrific recipe."
1244862,10125,5,Wonderfuly soft cookies! The kids and I both liked them. I used vanilla pudding and chocolate chips this time- I want to try it with chocolate pudding and pb/chocolate swirl chips next time!
168900,80470,4,"My DH loved these cookies, they were very soft and delicious. I don't know what I did wrong though, maybe I did not let the butter cool enough?? The dough was very runny so I had to add almost a cup of flour extra in order just to make it like dough to shape. I will keep trying though to tweek this one until it works though. Thanks!"
568241,87029,4,"Very soft and chewy, I guess I am just a sugarholic cause I thought they could be a little sweeter, I may add a little more sugar next time. Great recipe."
629317,13307,4,Pretty good. Only gave it 4 stars because it was too gritty. I know it's because of the oatmeal but I prefer a softer chewy cookie. But all in all it was really tasty.
84998,70294,5,"Everyone agreed that these are delicious. They're soft and chewy cookies, and they didn't get hard/tough the next day. It did take about 13 minutes in the oven per batch. If your oven is like mine, and doesn't heat evenly, I suggest you turn the sheet around in the oven about half way through the cooking time to get evenly baked cookies. Great recipe and one I'll make again."
1233692,190476,5,"Don&#039;t trust the bad reviews on this one! If you look at the bad reviews they pretty much have one thing in common - &quot;I started making the cookies but the dough looked too dry so I threw the instructions out the door and did my own thing and they turned out terrible!&quot;. Of course they didn&#039;t turn out you didn&#039;t follow the recipe! The top review said they didn&#039;t even bake the cookies they just tossed the dough because it didn&#039;t look right! Look people. This recipe isn&#039;t your traditional grease pancake recipe. Its amazing! But you have to follow the recipe exactly and the dough does turn out dry! BUT IT STILL WORKS! That being said I did add about 1/4 tsp of salt (although it&#039;s probably healthier without it) and when it says to mix the sugar and butter well, I mixed them until I had soft tips, added egg and vanilla and again mixed until I had soft tips. Make sure you don&#039;t over bake them (8 mins was perfect) if you do they might not be chewy. Seriously, These cookies turn out light and puffy and don&#039;t spread, which is what I like about them. If you like flatter cookies right when you pull them out of the over press them down with a spatula and they will still be amazing (though even then they are about 3/4 of an inch thick). In short, don&#039;t trust the bad reviews, trust the recipe and it will all be alright!"

In [32]:
sample_trait_reviews("crisp", 20)

Reviews containing 'crisp': 420

,RecipeId,Rating,Review
521622,22765,4,"My daughter and I left out the shortening and add in some rice crispies. Very good. They're still cooling in the kitchen, but we couldn't resist trying one."
1130783,218256,0,"These are the easiest, most delightful chocolate chip cookies I have ever made... In my opinion, the ideal cookie: crisp and golden brown on the outside, chewy and gooey on the inside. I have to say I am a tad confused about other reviews saying that they had so much trouble with these; mine came out to perfection. <br/><br/>I followed the recipe almost exactly, and used a stand mixer to combine all ingredients. I accidentally used 1/2 tsp. salt instead of 1/4, but they came out absolutely delicious! As recommended by another reviewer, I only used 1 1/4 cups chocolate chips, which is more than enough. I rolled the refrigerated cookie dough into 24 heaping tablespoon-sized balls and placed them on a dark, ungreased baking sheet, and actually baked for 15 minutes on the middle rack for a PERFECT cookie (found 8-10 minutes at an accurate 425? too short; the dough was still raw and pale). The key to getting them off the sheet onto a cooling rack is to have patience and let the cookies sit on the sheet for 2 minutes before attempting to transfer. Mine came right up, no problem. Delish! Definitely making them again..."
599876,30565,5,"These are so good! I love the combination of crispy and chewy and the recipe made a TON of cookies! I used only 1 cup of chocolate chips and it was plenty. I found that at 350, the cookies were browning a little too much on the bottoms, so I baked them at 335 degrees for about 10-11 minutes. So good! Thanks!"
1245400,20408,5,Almost perfect recipe. We cooked them on parchment paper on a cookie sheet. Which makes sure you get the good crisp edges. We also used a large scoop so we had the really good soft inside. I&#039;m going to have to play with the recipe to replace the pudding mix with cornstarch or cake flour because the flavor was just slightly off in my opinion.
1392714,100727,5,These are the BEST! I love that this recipe uses brown sugar instead of white. I also love the addition of crisco. It adds a little bit more crispness to the outside leaving the inside soft/chewy.
254914,53301,5,"These tasty little morcels should be given a 10+ star rating ! I haven't tasted anything so decadent and easy in a long time. As they were still warm from the oven each chocolate chip created an ooey goey chocolatey puddle with a slitely crispy exterior to each bite. You have to try these cookies. I had the neighborhood kids, My DH and DD ranting and raving over these ones. I am known as the cookie lady in my neighborhood and this one ranks on top. Be sure to have a cold glass of milk on hand... you'll need it. THANKS SO MUCH FOR AN AMAZING RECIPE !!!."
485279,39852,5,"These are good and chewy, not dry and crispy. They do make alot more than my blender could handle so towards the end of adding the six cups of flour I had to mix it by hand. Good cookies"
493014,80470,4,"I used this recipe when I forgot to take the butter out to soften for my usual recipe. We thought the flavor was good, but the cookies were more crisp than chewy. They disappeared quickly though! Thanks!"
127966,20408,5,A wonderfully soft and yet lightly crisp chocolate chip cookie. We all loved them. I omitted the almond extract only because they are going in a care package for a soldier in Iraq and I wasn't sure if he would like it. I think it sounds good though. Very pleased with how soft they are and am hoping they won't go *too* stale in the trip overseas. Great recipe!
250111,101041,5,Wonderful cookie recipe! I found that two packages (about 3 cups) of the swirled chips was perfect for us. The base had a wonderful flavor that stood up well to the sweetness of the chips. The edges were a little crispy and the middles a little chewy. Even DD's boyfriend proclaimed these REALLY good! A keeper for sure.
243511,138638,5,"I usually dont make cookies with butter flavored shortening but these were very good!! Both crisp and chewy at the same time, thanks for posting we will make these again!!"
333666,38041,5,"I finally found a great choc chip cookie recipe. For the longest time I'd been using the recipe on the nestle choc chip bag...with less than perfect results--usually the cookies were too flat/no bottoms/too crisp. With these recipe, the taste was exceptional, and the 'look' of the cookie was perfect in my opinion. I followed the recipe exactly, except chilled the dough between batches. Mine took nearly all of ten minutes and were a perfect combo of only slightly crisp on the outside and tender on the inside. This is my new standard for choc chip cookies. Thanks for a great recipe."
1245290,13307,3,"WARNING: DO NOT USE A Silpat Matt to bake cookies on! My first 2 batches of cookies flattened out and ran together. I had to cut them apart with a pizza cutter. For the 2nd two batch, I used parchment paper with better &amp; more ideal results. I love the slight texture the oatmeal adds to the cookies. The overall flavor is great, no sweeter than any other chocolate chip cookie I have ever eaten. Baking for 10 minutes results in a chewy cookie. I baked 5 minutes longer for a crispier cookie. Batch 2 still &quot;fell&quot; and flattened out but did not spread quit as much. Since this was too unpredictable, I am giving a 3 star rating for taste. I may try making them again one day to determine if it was pilot error or the recipe itself, and report back."
321262,166878,5,"These are delicious, chewy on the inside and crispy on the out..just the way I like chocolate chip cookies. I used a 250 gram packet of chocolate bits.\r\nThanks for sharing."
1092442,118487,5,"The kids LOVED these. A friend had made some crispy cookies my hubby liked more but the kids said these were a lot better - thick and chewy! So if you like thick and chewy, this is the cookie for you!"
1385486,147910,3,"Tasty cookies, but mine did not come out flat and crisp, nothing like Tate's. Probably operator error, since I had to skimp a little on the butter."
52260,13661,5,"Thank you, thank you, thank you! My first batch ever of chocolate chip cookies... made for my husband to take on a business trip (and for me to keep some as well). They were just PERFECT -- the best chocolate chip cookies ever. Left out the nuts, and couldn't find ""double chocolate chips"", so used Ghirardelli's semi-sweet and they were sooo wonderful. A little crisp, slightly chewy, NOT greasy. Perfect. Thanks so much for the great recipe!!"
834385,4050,5,"Truly the best cookie I have ever had. Light, crispy edges and a wonderful texture and flavor."
675333,331287,5,"These are yummy and easy to whip up! Who said there's such a thing as too much chocolate chips? lol I refrigerated them more than just overnight..uhmm..2 nights. Morning after I made them right away and it was so good! Ate them warm, I ate them cold, ate them even if I had a cold! Had it with a raspberry drink, had it with milk, love the crisp, love the chocolate chips. Love it! Love it! Just had to try it after LL raved about it in the Cookie Exchange Thread in the TOTM forum for Nov."
781033,271359,5,Nice little treat. I added the pecans as suggested. Crisp on the outside and a bit chewy on the inside. Perfect. Made for Every Day Tag :)

In [33]:
sample_trait_reviews("thick", 20)

Reviews containing 'thick': 195

,RecipeId,Rating,Review
1031310,358549,0,"Wow....hold on...I'm eating one of these as I type... Ok, phew!! Delicious!!! This was different from all of the other recipes that I have tried (even the recipes that have over 250 reviews at 4.5 starts) and this is by far the best. It does seem to need a touch more sugar, but overall...PERFECT. They turned out amazing! I followed the recipe without making any changes; however I did have to bake these for about 16 minutes. But that is totally fine with me... These were super easy to make since you don't have to wait for butter to come to room temperature! I typically don't like planning that far in advance. I'm an impulse baker and having to wait for butter to come to room temperature is a pain so another bonus by using this recipe! Try these! Next time I will add an additional 1/4 cup of sugar. These are going in my ""favorites"".<br/><br/>UPDATE: After these sat for a day... they were really hard and I could taste how prominent the salt was. Way too much salt! So... I'm now making these a 2nd time, but really tweaking this recipe. When made as-is, these cookies will get hard and they do not spread out when baking. For some I'm sure this is ok, but I like chewy/soft cookies...and trying to bake these thick cookies at 325 just doesn't cut it. You have to bake them longer to get them baked all the way through so in turn you are not getting soft cookies. Also, I don't really like baking cookies with shortening. So here's what I did this time... I like these much better!!! I used margarine instead of shortening... I used half the amount of salt and I added apple cider vinegar. For those of you who have never tried this - this will ensure your cookies are soft. This is a trick I learned from my mom who is an awesome baker."
270120,117317,5,Yummy! Words cannot express how excited I am about this recipe. The almond adds that little special something. The baking time was perfect. I added the extra flour to make my cookies puffy and thick. 10 stars all the way!!!
1141311,360266,5,"There is no other cookie recipe for me and the hub. After trying this Tyler Florence recipe, all other cookie recipes do not measure up. Thanks for posting DoubleA. I referenced this recipe often until I had it memorized from so many batches!<br/><br/>After making these cookies several times, these tweaks make the best cookies:<br/>1. Use Ghirardelli 60% bittersweet chocolate chips. The chocolate chips are shaped a little differently and melt a little differently so that you end up with ribbons of chocolate. You get a bit of chocolate in every bite. And the bittersweet chocolate keeps the cookie from being too sweet overall.<br/>2. Use unsalted butter, and, use just a pinch more salt than what is called for. I stick with kosher salt.<br/>3. After you mix your dough, use a 1/4 cup spring load ice cream scoop to pre-measure your dough into perfect little half-balls. Make the scoop absolutely level. Pop out into a large wax paper lined tupperware. Layering is okay. You end up with 16 cookie balls total, with about one spoonful of left over dough for the chef ;)<br/>4. Refrigerate your dough balls over night. After I started pre-measuring my cookies, I realized how awesome it was to have fresh cookies anytime I wanted them, rather than have half a batch of cookies go stale. And, I found that cookies from day before dough tasted better than same day cookies. I don't know why, they just do. The dough texture is totally different.<br/>5. Bake at 350, straight from fridge, for about 15 minutes. They should look just barely golden at the bottom and still a little doughy on top. They are a little thicker than a normal cookie and perfectly round. Let them sit on the cookie sheet for another 10-15 minutes. It will almost kill you, but I promise it is worth it. You end up with the perfect cookie - crisp on the bottom and practically still gooey in the center. They look, smell and taste perfect. So fabulous with milk."
839592,117317,5,"Great cookies! I used whole wheat pastry flour (2 3/4C) and they turned out great. I spread all the dough onto a smaller cookie sheet and then cut them into 2 dozen squares, which I transferred onto another cookie sheet to bake. They came out as nice big thick round cookies (trick I saw on the Today Show). Crispy on the outside and soft on the inside - as advertised. Thank you!"
654497,4050,4,"I needed a quick and yummy recipe for a friend who just wrecked his shoulder for a get-well present, and these were a really nice choice. I halved the recipe, and followed everything to a proportional tee. I made half the batch with chocolate chips&pecans, the other half with just chocolate chips. The cookies came out a little thin for my liking (especially because the photos showed thicker cookies), but I really enjoyed the fabulous flavor in the cookies with the pecans. I gave the recipe a 4 out of 5 because these were good; but I have had better...or maybe my expectations were too high after seeing the average 5 star rating after 43 reviews. I am keeping this recipe however!"
1112133,100727,5,"Just as advertised! Thick, soft and chewy! What more could you want in your chocolate chip cookie? This will now be my go to recipe for CCC! Thanks for posting!"
566122,53301,5,"Yum!!! I did double the recipe, and I'm glad I did. I was concerned that 5 sticks of butter was going to make them greasy, but they weren't. The batter was pretty thick and it did make so much that my Kitchenaid stand mixer found it kind of tough to mix, but we made it. I can't stand crunchy, overbaked cookies, so I took out my first several sheets right at 8 minutes, and then let them sit for 5 minutes or so before moving them to the cooling rack. I didn't taste one until all I had left was my last sheet, and I decided then to leave that last sheet in for 9 minutes. I think those were better. They were still pretty doughy at 8 minutes. These are very sweet, but I wouldn't change a thing! I got 6 dozen 2 inch cookies. I liked the looks of the ones I flattened a bit better than ones I didn't. Fantastic cookies, and I'm excited to have a new cookie to add to my collection."
231241,117317,5,"The taste and texture of this cookie is truly one of the best chocolate chip cookies I have made. It is a cookie that holds its shape (doesn't spread) and is chewy and thick. I followed the recipe exactly, but I did line the cookie sheet with parchment paper to prevent even more spreading. The vanilla and almond extracts combo pushes this cookie to the top of my list. When you bite into the cookie it is crunchy on the outside and chewy inside. I will certainly make this again and again! Thanks Roxygirl in Colorado for a keeper!"
892584,80470,5,"My boys like softer thicker chocolate chip cookies, and these are the best I have ever tried. This recipe is a keeper"
890310,80470,5,"By far the best chocolate chip recipe. I have always liked the cookies best right out of the oven still warm, however, these cookies are not best right out of the oven. They are actually best the next day. I took them to work to share with my co-workers and they all raved about them. The cookies are nice and thick, they don't flatten out like most. The pic on the recipe is not a good representation. The one with the cookies and milk are how they actually look. Thanks for posting the great recipe! I will be using this one again!!"
1344673,48356,5,"First time trying a recipe using margarine instead of butter. They turned out great! Soft and thick, didn't flatten or spread."
284855,93865,2,"As far as chocolate chip cookies go, this was not to my families liking. I followed the recipe to the letter and they came out tasting very sweet, and the crisco stands out. (not sure why, it's a small amount) They do turn out thick and beautiful, we just didn't care for the taste. Thank you for sharing."
738418,356866,5,"What a great idea this is! I creamed the butter with the sugars, added the vanilla extract and water and then stirred in the flour, baking soda and finally the chips. I made one 5"" round, thick cookie. I think this would be nice to wrap in cellophane and bring to a coworker or friend for their birthday or special occasion. Just a little something that would be fast to make and taste delicious. Thanks for posting this!"
135044,10289,4,These were very good--thick and crispy on the outside and chewy on the inside. I added an extra teaspoon of vanilla and omitted the nuts. My kids loved them!
1244710,10125,5,"Great cookie recipe. I made this recipe and recipe #296761, which is very similar. This recipe created cookies that were thicker and did not spread as much. We liked these better, however it is a personal preference as we could detect no difference in the taste. The cookies are great with a sweet flavor and a soft chewy texture. I used a 5 oz box of pudding because it was what I had. I also added 1/4 t of salt since I was using unsalted butter. I baked my cookies for 8 minutes. Cooling on the sheet is an important step. Again great cookies and thank you for the recipes. I got 47 cookies using a small cookie scoop."
916626,218256,5,"My daughter keeps requesting a thin chocolate chip cookie (the opposite of the hearty ones that I love!). She even made the dough! We found around a cup & 1/4 of chips plenty. The cookies baked up PERFECTLY (level but still sturdy). They were thicker than the photo. Both batches baked up consistently. The flavor was the BEST and the texture delighted my daughter and me (plus the rest of the family). I froze the dough for 25 min. You are the ""Queen of the chocolate chip cookies!"" Thanks for posting.\nRoxygirl"
656424,41862,5,"GREAT cookie pizza, perfectly round and beautiful!! I used a 14 inch LIPPED pizza pan that I lined with parchment cut a little larger than the pan, and creased at the edge of the lip. This totally controlled the cookie dough, which I spread all the way to the edge. I did use 1/2 cup shortening and 1/2 cup butter, which always decreases the amount of ""cookie spread"". I decreased the salt to 1/2 teaspoon and used about 1 3/4 cups chocolate chips (part semisweet and part milk chocolate). I baked at 350 and it didn't overbrown... and NO overflow. It was thick and soft, and cut great with a pizza cutter."
905547,142029,4,"I just made these tonight. They taste great, but were certainly more ""done"" than the ones in the picture. 18 minutes was a bit too much. I used two different types of pans, a well-seasoned stoneware pan and a couple of Calphalon baking pans. I thought that there was enough butter in the recipe that I didn't need to grease my pans, and the recipe didn't mention it, either. I was wrong. These cookies stuck to both types of pans and were very hard to remove. \r\n\r\nThe first ones into the oven were the size specified in the recipe, on the stoneware pan, as were the ones on the metal pans. I baked the ones on the stoneware pan for 18 min. and the ones on the metal pans for 17 min. The cookies came out well done and crispy on the outside (not just on the edges). I wouldn't call them thick, but they were certainly big in diameter and slightly thicker than the recipe I normally use.\r\n\r\nThe last ones into the oven went on the stoneware pan again, which I scraped clean and then greased. Since it was already warm, the dough began to spread out (as would be expected). I made these ones a little smaller and baked them for about 15 min. I should have reduced the time further, as they came out overdone and very difficult to get off the pan. What a mess."
1378085,53301,5,"If you love chocolate the you will love these cookies. I read through many reviews and did tweak the recipe based on the many ideas I read. SOME people complained about a dry, flat cookie so I lowered the flour by 1/2 cup and that probably helped with the dryness. I also did half sugar/half brown sugar. The cookies came out of the oven puffy but did flatten out as they cooled. But I care more about taste and texture that I do about thickness and these cookies were nice and chocolate-y and moist. No one had a problem eating more than one, lol."
933332,117317,5,"These cookies are fabulous! I did use the 2 3/4 c. flour and they were thick and chewy and did not spread much at all. I used a cookie scoop for mine. I do not like flat crisp cookies, so these were perfect for me. The kids loved these and they couldn't get enough. Same with their friends. I did not care much for the taste of the dough and as my husband loves to eat cookie dough, he didn't like it much either, but he absolutely loved the baked cookie! These will be made often. Thanks for another fabulous chocolate chip cookie."

In [34]:
sample_trait_reviews("thin", 20)

Reviews containing 'thin': 1084

,RecipeId,Rating,Review
937506,20408,5,These were awesome cookies. I loved that they didn't flatten. I did use regular shortening and next time I think I will use the butter flavoring for extra flavor. Thanks for sharing a great recipe.
92285,10429,3,"These cookies are just okay. If I ever make them again I think I would add another egg. Also, 12 minutes in the oven would be far too long."
463899,100727,5,"This is the first time I made a soft chocolate chip cookie. Usually when I make them they are more crisp and crunchy. These were very good. Nice and soft and chewy. I like these much better than the thinner crispy chocolate chip cookies. I had 1/2 a cup of white chocolate chips that I wanted to use up, so I used the 1/2 cup of white chocolate chips and 1 cup of the semi-sweet chocolate chips. I also added a cup of chopped pecans. These cookies were excellent. I will be making my chocolate chip cookies this way from now on. Thanks for sharing such a wonderful recipe, Marg."
1327855,20408,5,"These are yummy! My whole family loved them and they were flying off the rack before they could cool. It made a lot, so they are getting extra treats in their lunch boxes. I think the vanilla pudding mix is a great addition in cookies."
338035,39641,5,"I cannot believe that this recipe has been on Zaar for 5 years and yet no one has ever reviewed it!! You all are missing out! These cookies are FANTASTIC! A 10-star recipe all the way. Absolutely everyone who has tried one has raved about them. I made them exactly as written, using walnuts and peanut butter chips. Even though I think some various combinations of nuts and chips might be fun, make sure you don't omit the butter brickle pieces; they really add a unique dimension to these cookies. I will definitely be making them again! I would suggest checking them at 9 minutes since in my oven they were a bit overdone at 10 minutes. Thank you so much for sharing this fantastic recipe! I'm only sorry I didn't find it sooner!"
128406,81016,5,"I've never made cookies where you mix everything all together in one bowl, so I did it my usual way.Using my Kitchen Aid I creamed the Crisco and sugar till fluffy,then added the eggs and vanilla, mixed that up and then added the flour and mixed up, then the choc. chips. I had miniature chips so only used 1 cup. I got 28 cookies using a 2"" cookie scoop. They did spread quite a bit but they turned out delicious.I baked for 14 minutes. Turned out nice and crisp, just the way we like them. Thanks for your mom's recipe."
624607,293380,4,These are wonderful cookies. I liked the texture of the cookie and they did keep soft for a day. I used semi-sweet chips just as that is what I had on hand but everything else remained the same. Made for PAC April 2008.
706954,332767,5,I really did think these were pretty great! I halved the recipe because I wanted to see how they'd come out and was not disappointed. I baked them 9 - 10 minutes so they came out soft in the middle and crispy on the sides. Also - I added 1 tsp of vanilla extract and 1 tsp of peppermint extract (instead of 2 tsp vanilla) so it was like biting into a mint-chocolate. Loved them and will be making these with several variations. Thanks for the recipe blucoat.
470628,258922,5,"Very tasty cookies! I used 2 cups milk chocolate chips and 2 cups white chocolate chips just for something different, but the cookies would have been deelish no matter what chips or nuts you added. A definate keeper! Thanks!"
836892,101041,4,"Perfect texture!!! I couldn't get to my usual chocolate chip cookie recipe since moving, so I looked for a highly rated one on here and found this one. The texture of these are exactly like m other ones, which I love, and while they taste really good, theres something about the flavour that isn't quite as good as my other recipe (thats the one star loss). \nI did make these with chunks of dark chocolate instead of chocolate chips though, very yummy!"
487694,181387,5,"These were GREAT! My son is also allergic to dairy products, so I used a dairy-free margarine, and chocolate chips that are ""allergen free."" I thought that the consistency/texture of the cookie would suffer because of the margarine and lack of a real egg, but it really is just like a Toll House cookie! I use a medium cookie scoop (looks like an old fashioned ice cream scoop with a spring--you can get them at places like Linens and Things or through Pampered Chef) and I have found that this helps create that chewy center. The scoop also gives each cookie that nice round shape. It's so nice to finally have a chocolate chip cookie that the whole family can enjoy!"
1014077,80470,5,"It almost seems pointless to review these cookies, since it's clear at this point how delicious they are, but I am one more satisfied baker. The cookies turn out super thick (if you leave them in ball form and don't flatten at all) but I kind of liked that because the dense, moist middle was the best part for me. Like others, I did not refrigerate the dough for too long and the cookies still turned out perfectly. I think my baking time worked out to be a little bit closer to 7 minutes on each rack.<br/><br/>Phenomenal recipe! Will definitely be making them again (especially since they don't involve some of the more esoteric ingredients that other recipes call for)!"
242037,99267,5,Made this exactly as posted after my daughter requested something sweet. This fit the bill. Thanks so much for sharing.
172435,101041,5,"Very good cookie; soft and moist. I scaled down the recipe to 24 servings and used 2 eggs instead of the scaled down 1 1/3. First 2 batches were baked on a Cushionaire cookie sheet (the kind with the air pocket in between top and botton layers of the cookie sheet)and they spread more than I liked. Last batch was made on a cheap cookie sheet, darker than the 1st one I used and baked beautifuly. They didn't spread too thin like the first 2 batches. You do need to reduce baking time and probably temperature when baking on the darker cookie sheets. I will be making these again!"
837001,38041,5,Awesome cookies! The only thing I did differently was add a little more than 1/4 cup of walnuts to the mix. Perfect!
1362098,100727,5,These are great cookies. Don't tweak a thing.
1256164,26849,3,"Did everything the recipe said, minus using margarine instead of butter. I&#039;m not sure if that was the big issue, but I didn&#039;t care for these cookies. They were very flour-y and cake-like. Moist, yes, but just weren&#039;t that great. The chocolate chips I used seemed to save them (Hershey Milk Chocolate chips - half a bag). I&#039;ll try another recipe and use butter next time. A little lackluster."
1244882,10125,5,"My entire family loves these cookies. They are usually gone in less than a day. My DH who thinks his grandmother makes the best everything, even said they wre better than hers. Finially something I made was as good or better than Nana's. Thanks for the recipe. This is the only Chocolate Chip recipe we have made in the last two years"
1032995,190476,3,This is a fair basic chocolate chip cookie recipe but unfortunately somewhere in your measurements something is wrong as the dough is extremely dry and very crumbly. There is no way you can make a cookie out of the original measurements. To save the dough I added one egg white and then the dough was workable. They still bake up in mounds - no spreading at all and still are a bit crumbly/dry. I'm sorry this just did not work as well as expected. Made for Zaar Cookbook tag.
1345095,378778,5,Best chocolate chip cookie recipe ever! I remember as a young girl buying the Betty Crocker recipe book that came in a binder. I baked these cookies for my children when they were young. the only thing that I did differently was add an extra 1/2 cup of flour and a teaspoon of baking powder. Cookies always came out nice thick and chewy!

# Cookie Lab: Texture Phenotype Audit

## Goal

The objective of this analysis is to determine whether recipe reviews can be used to extract measurable cookie characteristics ("cookie phenotypes").

Instead of classifying cookies into one category, Cookie Lab treats cookies as a combination of physical traits:

- Softness
- Chewiness
- Crispness
- Thickness
- Spread / Thinness
- Moisture
- Cakiness
- Gooeyness

Reviews were analyzed to determine whether users naturally describe these characteristics and whether they provide enough signal for future NLP modeling.

---

# Dataset Overview

Source:
Food.com Recipes and Reviews Dataset

## Initial Dataset

Recipes:
- 522,517 recipes
- 28 attributes

Reviews:
- 1,401,982 reviews
- 8 attributes


## Chocolate Chip Cookie Subset

Recipes identified through:

- Recipe category
- Recipe title matching
- Chocolate chip cookie keywords

Final subset:

Recipes:
- 1,258

Reviews:
- 5,651

Recipes with at least one review:
- 631


---

# Chocolate Chip Cookie Identification

The dataset contained an existing category:

In [36]:
classic_candidates["RecipeCategory"].value_counts()

RecipeCategory
Drop Cookies              606
Dessert                   491
Chocolate Chip Cookies    108
Bar Cookie                  8
Frozen Desserts             8
< 30 Mins                   8
Pie                         7
Breakfast                   3
Quick Breads                2
Beverages                   2
Sweet                       2
< 60 Mins                   2
Cheesecake                  1
Tarts                       1
Kid Friendly                1
Grains                      1
Canadian                    1
Toddler Friendly            1
Ice Cream                   1
Nuts                        1
Shakes                      1
Candy                       1
< 15 Mins                   1
Name: count, dtype: int64

In [37]:
classic_candidates[
    classic_candidates["RecipeCategory"].isin([
        "Bar Cookie",
        "Frozen Desserts",
        "Pie",
        "Breakfast",
        "Quick Breads",
        "Beverages",
        "Cheesecake",
        "Tarts",
        "Ice Cream",
        "Shakes",
        "Candy"
    ])
][["Name", "RecipeCategory"]]

,Name,RecipeCategory
16742,Chocolate Chip Cookie Turtle,Bar Cookie
23254,Jumbo Chocolate Chip Cookie,Bar Cookie
42856,Chocolate Chip Cookie Gift Mix,Bar Cookie
69291,Fluffy Chocolate Chip Cookies,Quick Breads
92813,Chocolate Chip Cookie Milkshake,Frozen Desserts
93884,Chocolate Chip Cookie Pie,Pie
107421,Granola Chocolate Chip Cookies,Breakfast
121808,Chocolate Chip Cookie Pie,Pie
129535,Oats 'n Caramel Chocolate Chip Cookie Squares,Bar Cookie
143114,Chocolate Chip Cookie Martini,Beverages
174493,Cranberry Trail Mix Chocolate Chip Cookies,Breakfast
175539,Chocolate Chip Cookie Muffins,Quick Breads
205642,Chocolate Chip Cookie Ice Cream Cake,Frozen Desserts
217628,Chocolate Chip Cookie Pie,Pie
243121,No Bake Chocolate Chip Cookie Pie,Pie
258125,Chocolate Chip Cookie Pie,Pie
266473,Chocolate Chip Cookie Pie,Pie
270056,Chocolate Chip Cookie Cheesecake,Bar Cookie
302416,Skillet Baked Chocolate Chip Cookies,Bar Cookie
305081,Chocolate Chip Cookie Ice Cream Cake from Recipe4living,Frozen Desserts
305674,Chocolate Chip Cookie Delite,Bar Cookie
324241,Slice & Bake Chocolate Chip Cookie Roll,Frozen Desserts
348722,Chocolate Chip Cookie Cheesecake Bites,Cheesecake
349123,Chocolate Chip Cookie and Cream Tart,Tarts
359435,Easy Ice Cream/Chocolate Chip Cookie Pie,Frozen Desserts
362314,Cookie Ice Cream Sandwiches- Chocolate Chip Cookies,Frozen Desserts
368185,Chocolate Chip Cookies Ice Cream Sandwich,Frozen Desserts
416707,A Drinkable Chocolate Chip Cookie Experiment,Beverages
423719,Chocolate Chip Cookies,Bar Cookie
448336,Sleepy Time Chocolate Chip Cookies,Frozen Desserts
459695,Chocolate Chip Cookie Ice Cream Cake,Ice Cream
468397,Om Nom Nommers Chocolate Chip Cookie,Shakes
483989,Coconut Chocolate Chip Cookies,Breakfast
488439,"Giant, Chewy, Brown Butter Toffee Chocolate Chip Cookies",Candy
516311,Chocolate Chip Cookie Slab Pie,Pie

In [38]:
classic_cookies_clean = classic_candidates[
    classic_candidates["RecipeCategory"].isin([
        "Drop Cookies",
        "Chocolate Chip Cookies",
        "Dessert"
    ])
]

print(classic_cookies_clean.shape)

(1205, 28)

In [39]:
classic_cookies_clean[
    ~classic_cookies_clean["Name"].str.contains(
        "cookie",
        case=False,
        na=False
    )
][["Name","RecipeCategory"]]

Empty DataFrame
Columns: [Name, RecipeCategory]
Index: []

In [40]:
classic_cookies_clean["RecipeCategory"].value_counts()

RecipeCategory
Drop Cookies              606
Dessert                   491
Chocolate Chip Cookies    108
Name: count, dtype: int64

In [41]:
classic_cookies_clean[["Name", "RecipeCategory"]].sort_values("Name")

                                                  Name          RecipeCategory
509605                       #1 Chocolate Chip Cookies  Chocolate Chip Cookies
169322              $250 Chocolate Chip Cookies Recipe                 Dessert
239908              $250 Chocolate Chip Cookies Recipe                 Dessert
112890                  $250.00 Chocolate Chip Cookies            Drop Cookies
495594   &quot;Indonesian&quot; Chocolate Chip Cookies  Chocolate Chip Cookies
...                                                ...                     ...
159320                 Zander's Chocolate Chip Cookies                 Dessert
277079                    Zippy Chocolate Chip Cookies            Drop Cookies
419446  Zoey's Healthier Fluffy Chocolate Chip Cookies  Chocolate Chip Cookies
243762                 Zucchini Chocolate Chip Cookies            Drop Cookies
492099                 Zucchini Chocolate Chip Cookies            Drop Cookies

[1205 rows x 2 columns]

In [43]:
classic_cookies_clean[
    classic_cookies_clean["Name"].str.contains(
        "bar|cake|pie|brownie|cupcake|muffin|ice cream|sandwich|dough|mix|turtle|martini|drink",
        case=False,
        na=False
    )
][["Name","RecipeCategory"]]

,Name,RecipeCategory
40980,Chocolate Chip Cookie Mix,Drop Cookies
44551,Chunky Chocolate Chip Cookie Mix in a Jar,Dessert
44555,Chocolate Chip Cookie Mix in a Jar,Drop Cookies
67310,Chocolate Chip Cookie Mix in a Jar,Drop Cookies
93757,Decadent Chocolate Chip Cookies(Cake Mix),Drop Cookies
117770,Ultimate Chocolate Chip Cookies in a Jar Mix,Dessert
141061,Chocolate Chip Cookie Cupcakes,Dessert
160992,Kentucky Pie (Giant Chocolate Chip Cookie Pie With Nuts),Dessert
192581,"Cranberry, Bittersweet Chocolate Chip Cookies in a Jar Mix",Drop Cookies
192583,Chocolate Chocolate Chip Cookies in a Jar Mix,Drop Cookies
193268,Coffee Chocolate Chip Cookie Mix in a Jar,Drop Cookies
244125,Chocolate Chip Cookie Cupcakes (Gift Mix in a Jar),Dessert
264909,Easy Bake Oven Chocolate Chip Cookie Mix,Drop Cookies
281988,Even Healthier Chocolate Chip Cookies/Muffinish,Dessert
297754,Chocolate Chip Cookie Cupcakes,Dessert
298066,Make-A-Mix Chocolate Chip Cookies,Drop Cookies
381428,Quick Mix Chocolate Chip Cookies W/O Chocolate Chips :),Drop Cookies
412726,Ice Cream Chocolate Chip Cookies,Drop Cookies
425571,Hi-Hi&rsquo;s Chocolate Chip Cookie Sandwiches,Dessert
458246,Chocolate Chip Cookie Poke Cake,Dessert
463876,Nutella Chocolate Chip Cookie Icebox Cake,Dessert
470259,Sourdough Chocolate Chip Cookies,Drop Cookies
497384,Chocolate Chip Cookie Mini Cheesecakes,Chocolate Chip Cookies
499078,Jessica's Mix and Match Chocolate Chip Cookies,Chocolate Chip Cookies
512086,Cori's Cakey Chocolate Chip Cookies,Chocolate Chip Cookies
512175,Kellogg's Rice Krispies Chocolate Chip Cookies,Dessert
520634,12 Cake-Like Chocolate Chip Cookies for Miles,Dessert

In [44]:
remove_words = [
    "mix",
    "jar",
    "cupcake",
    "cake",
    "cheesecake",
    "pie",
    "sandwich",
    "icebox",
    "poke"
]

pattern = "|".join(remove_words)

classic_cookies_final = classic_cookies_clean[
    ~classic_cookies_clean["Name"].str.contains(
        pattern,
        case=False,
        na=False
    )
]

print(classic_cookies_final.shape)

(1180, 28)

In [45]:
classic_cookies_final[["Name","RecipeCategory"]]

                                                   Name RecipeCategory
1828                 Mrs. Fields Chocolate Chip Cookies   Drop Cookies
2109                  Best Basic Chocolate Chip Cookies   Drop Cookies
2492      Canadian Living's Best Chocolate Chip Cookies   Drop Cookies
2493        Mike's Grand Marnier Chocolate Chip Cookies   Drop Cookies
2529                             Chocolate Chip Cookies   Drop Cookies
...                                                 ...            ...
521670               Scrumptious Chocolate Chip Cookies        Dessert
521671               Scrumptious Chocolate Chip Cookies        Dessert
521674  Lindsay's Chocolate Cafe Chocolate Chip Cookies        Dessert
522156           BEST EVER CHEWY CHOCOLATE CHIP COOKIES        Dessert
522370                           CHOCOLATE CHIP COOKIES        Dessert

[1180 rows x 2 columns]

In [46]:
classic_cookies_final["Name"].duplicated().sum()

np.int64(330)

In [47]:
classic_cookies_final[
    classic_cookies_final["Name"].duplicated(keep=False)
][["Name","RecipeCategory"]].sort_values("Name")

                                              Name          RecipeCategory
169322          $250 Chocolate Chip Cookies Recipe                 Dessert
239908          $250 Chocolate Chip Cookies Recipe                 Dessert
494530         4 Ingredient Chocolate Chip Cookies  Chocolate Chip Cookies
512397         4 Ingredient Chocolate Chip Cookies                 Dessert
29265   Absolutely the Best Chocolate Chip Cookies            Drop Cookies
...                                            ...                     ...
243057                Yummy Chocolate Chip Cookies            Drop Cookies
336862                Yummy Chocolate Chip Cookies                 Dessert
359318                Yummy Chocolate Chip Cookies            Drop Cookies
243762             Zucchini Chocolate Chip Cookies            Drop Cookies
492099             Zucchini Chocolate Chip Cookies            Drop Cookies

[421 rows x 2 columns]

In [48]:
duplicate_names = classic_cookies_final[
    classic_cookies_final["Name"].duplicated(keep=False)
]["Name"]

classic_cookies_final[
    classic_cookies_final["Name"].isin(duplicate_names)
][["RecipeId", "Name", "AuthorName"]].sort_values("Name")

        RecipeId                                        Name       AuthorName
169322  177187.0          $250 Chocolate Chip Cookies Recipe            SaraC
239908  249746.0          $250 Chocolate Chip Cookies Recipe            Rissy
494530  512710.0         4 Ingredient Chocolate Chip Cookies  Bakers 5th Rush
512397  530937.0         4 Ingredient Chocolate Chip Cookies        Neriah M.
29265    32852.0  Absolutely the Best Chocolate Chip Cookies       Carrie Ann
...          ...                                         ...              ...
243057  252982.0                Yummy Chocolate Chip Cookies           lrl418
336862  349520.0                Yummy Chocolate Chip Cookies          See-Jay
359318  372470.0                Yummy Chocolate Chip Cookies       Meghan lt3
243762  253705.0             Zucchini Chocolate Chip Cookies           mommaj
492099  510216.0             Zucchini Chocolate Chip Cookies    Member 610488

[421 rows x 3 columns]

### Checked duplicates, inspected ID to make sure they were not the same recipes

In [49]:
classic_cookies_final[
    classic_cookies_final["Name"] == "Yummy Chocolate Chip Cookies"
][[
    "RecipeId",
    "Name",
    "RecipeIngredientParts",
    "RecipeInstructions"
]]

,RecipeId,Name,RecipeIngredientParts,RecipeInstructions
243057,252982.0,Yummy Chocolate Chip Cookies,"[all-purpose flour, baking soda, salt, butter, granulated sugar, brown sugar, vanilla extract, eggs]","[Preheat oven to 375., Beat together butter and sugar until creamy., Add Vanilla., Beat in Eggs one at a time., In a seperate bowl, combine flour, baking soda and salt in small bowl., Slowly add the flour mixture into the wet mixture., Stir in choc.chips. (Add nuts at this point too if you'd like)., Roll dough into little balls, about 1 tablespoon each, and place onto ungreased baking sheets., Bake for 11 minutes or until golden brown., Cool on baking sheets for 2 minutes; remove to wire racks to cool completely., ENJOY!]"
336862,349520.0,Yummy Chocolate Chip Cookies,"[vegetable shortening, white sugar, white sugar, brown sugar, brown sugar, vanilla, water, egg, flour, salt, baking soda]","[Preheat oven to 375 degrees., Beat shortening in mixer until fluffy., Add both sugars and beat for several minutes; until light and fluffy., Add vanilla, water, and egg. Beat until incorporated., In a seperate bowl, mix together the flour, salt, and baking soda., SLOWLY add the dry ingredients to the wet mixture and stir on low for several seconds., Add the chocolate chips., Using a scooper, place each ball of dough onto a cookiesheet., Bake for 8-10 minutes; or until you stick a toothpick in a cookie and it comes out clean.]"
359318,372470.0,Yummy Chocolate Chip Cookies,"[butter, brown sugar, white sugar, vanilla, egg, flour, baking soda, salt, cornstarch]","[Preheat oven to 325 degrees F., Cream together butter, sugar and vanilla. Add egg., In a seperate bowl, sift together flour, soda, salt and starch., Mix into creamed mixture., Add chocolate chips., Drop by tablespoons on a wax or parchment paper lined cookie sheet., Bake for about 12 minutes, or until golden brown., Let cool on the cookie sheet for about a minute. Then transfer to cookie sheet for further cooling.]"

In [53]:
%whos

Variable                     Type         Data/Info
---------------------------------------------------
choc_chip_candidates         DataFrame    Shape: (1775, 28)
classic_candidates           DataFrame    Shape: (1258, 28)
classic_cookie_reviews       DataFrame    Shape: (5515, 35)
classic_cookies_clean        DataFrame    Shape: (1205, 28)
classic_cookies_final        DataFrame    Shape: (1180, 28)
classic_ids                  Series       Shape: (1258,)
classic_reviews              DataFrame    Shape: (5651, 8)
classic_with_review_counts   DataFrame    Shape: (1258, 29)
cookie_categories            list         n=3
drop_cookies                 DataFrame    Shape: (826, 28)
duplicate_names              Series       Shape: (421,)
exclude_mask                 Series       Shape: (1775,)
exclude_terms                list         n=22
high_confidence              DataFrame    Shape: (144, 28)
kagglehub                    module       <module 'kagglehub' from <...>s/kagglehub/__init__.py'>
likely_cookies               DataFrame    Shape: (1650, 28)
mask                         Series       Shape: (5651,)
n_recipes                    int          18
n_reviews                    int64        27
name_lower                   Series       Shape: (1775,)
os                           module       <module 'os' (frozen)>
other_candidates             DataFrame    Shape: (805, 28)
path                         str          /Users/abbygoblick/.cache<...>es-and-reviews/versions/2
pattern                      str          mix|jar|cupcake|cake|chee<...>|pie|sandwich|icebox|poke
pd                           module       <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
phenotype_terms              list         n=17
recipes                      DataFrame    Shape: (522517, 28)
recipes_path                 str          /Users/abbygoblick/.cache<...>ersions/2/recipes.parquet
remove_words                 list         n=9
review_counts                Series       Shape: (631,)
reviews                      DataFrame    Shape: (1401982, 8)
reviews_path                 str          /Users/abbygoblick/.cache<...>ersions/2/reviews.parquet
sample_trait_reviews         function     <function sample_trait_reviews at 0x1468d7480>
term                         str          dense

In [51]:
classic_cookie_reviews.head()

,ReviewId,RecipeId,AuthorId_x,AuthorName_x,Rating,Review,DateSubmitted,DateModified,Name,AuthorId_y,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,19,13307,2046,Gay Gilmore ckpt,5,"chewy goodness, not crispy at all. i even threw in craisins and left the oatmeal whole, and they were great.",2000-05-21 16:59:00+00:00,2000-05-21 16:59:00+00:00,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,20914,...,4.5,18.5,127.6,22.8,1.5,13.9,2.5,NaN,96 cookies,"[Measure oatmeal and blend in a blender to a fine powder., Cream the butter and both sugars., Add eggs and vanilla., Mix together with flour, oatmeal, salt, baking powder and soda., Add chocolate chips, grated Hershey Bar and nuts., Roll into 1 inch balls and place 2-inches apart on a cookie sheet., Bake for 10 minutes at 375° or until golden.]"
1,253,13307,4200,LC Liu,5,"I received this ""hoax"" email forward about 4 years ago, but never attempted the recipe. A friend of the family made it for us just a few weeks ago and it tastes incredible! I can't believe I held on to this recipe for so long!!",2001-01-02 16:32:03+00:00,2001-01-02 16:32:03+00:00,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,20914,...,4.5,18.5,127.6,22.8,1.5,13.9,2.5,NaN,96 cookies,"[Measure oatmeal and blend in a blender to a fine powder., Cream the butter and both sugars., Add eggs and vanilla., Mix together with flour, oatmeal, salt, baking powder and soda., Add chocolate chips, grated Hershey Bar and nuts., Roll into 1 inch balls and place 2-inches apart on a cookie sheet., Bake for 10 minutes at 375° or until golden.]"
2,585,4051,7209,Jazzy,4,"This makes a lovely chocolate chip cookie, but I couldn't taste the Grand Marnier. Perhaps adding a bit of orange zest would enhance the orange flavor.",2001-03-29 17:11:32+00:00,2001-03-29 17:11:32+00:00,Mike's Grand Marnier Chocolate Chip Cookies,1556,...,2.8,10.3,100.6,20.1,1.0,12.4,1.8,NaN,36 cookies,"[Cream margarine, sugars, vanilla and Grand Marnier in a large mixing bowl., Add eggs, beating well after each addition., Add baking soda and flour and stir until blended., Stir in oats, then chocolate chips., Drop by the tablespoonfuls 5 cm apart onto ungreased cookie sheets., Bake at 300°F for 5-10 minutes or until done. Allow to cool somewhat before removing from cookie sheet.]"
3,586,13307,7230,Sadie Schilk,5,"This recipe is awesome! I tried it out of curiosity, brought the cookies to work, and everyone loved them. They fought over who was going to eat the last one. It makes about a million cookies, so unless you are sharing it with a large number of people, cut the recipe in half, or you will have more cookies than you know what to do with!",2001-03-29 17:11:32+00:00,2001-03-29 17:11:32+00:00,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,20914,...,4.5,18.5,127.6,22.8,1.5,13.9,2.5,NaN,96 cookies,"[Measure oatmeal and blend in a blender to a fine powder., Cream the butter and both sugars., Add eggs and vanilla., Mix together with flour, oatmeal, salt, baking powder and soda., Add chocolate chips, grated Hershey Bar and nuts., Roll into 1 inch balls and place 2-inches apart on a cookie sheet., Bake for 10 minutes at 375° or until golden.]"
4,630,3307,7673,Rachel Merrell,1,"dough is too thin, the cookies melted together and they came out really thin. Flavor was ok.",2001-04-04 16:51:30+00:00,2001-04-04 16:51:30+00:00,Mrs. Fields Chocolate Chip Cookies,1763,...,4.3,21.7,66.3,14.9,0.6,11.9,1.0,NaN,42 cookies,"[Heat oven to 300°F., Combine flour, baking soda and salt in medium bowl using whisk; set aside., Mix sugars in bowl with an electric mixer on medium speed., Add butter; beat until grainy paste forms., Beat in eggs and vanilla on medium speed until light and fluffy., Add flour mixture and chocolate chips., Beat on low speed just until mixed., Do not over mix., Drop dough by rounded tablespoons onto ungreased baking sheets, 2-inches apart. Bake for 22 minutes until golden brown., Transfer cookies to cooling rack.]"

In [54]:
classic_cookie_reviews.head()

,ReviewId,RecipeId,AuthorId_x,AuthorName_x,Rating,Review,DateSubmitted,DateModified,Name,AuthorId_y,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,19,13307,2046,Gay Gilmore ckpt,5,"chewy goodness, not crispy at all. i even threw in craisins and left the oatmeal whole, and they were great.",2000-05-21 16:59:00+00:00,2000-05-21 16:59:00+00:00,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,20914,...,4.5,18.5,127.6,22.8,1.5,13.9,2.5,NaN,96 cookies,"[Measure oatmeal and blend in a blender to a fine powder., Cream the butter and both sugars., Add eggs and vanilla., Mix together with flour, oatmeal, salt, baking powder and soda., Add chocolate chips, grated Hershey Bar and nuts., Roll into 1 inch balls and place 2-inches apart on a cookie sheet., Bake for 10 minutes at 375° or until golden.]"
1,253,13307,4200,LC Liu,5,"I received this ""hoax"" email forward about 4 years ago, but never attempted the recipe. A friend of the family made it for us just a few weeks ago and it tastes incredible! I can't believe I held on to this recipe for so long!!",2001-01-02 16:32:03+00:00,2001-01-02 16:32:03+00:00,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,20914,...,4.5,18.5,127.6,22.8,1.5,13.9,2.5,NaN,96 cookies,"[Measure oatmeal and blend in a blender to a fine powder., Cream the butter and both sugars., Add eggs and vanilla., Mix together with flour, oatmeal, salt, baking powder and soda., Add chocolate chips, grated Hershey Bar and nuts., Roll into 1 inch balls and place 2-inches apart on a cookie sheet., Bake for 10 minutes at 375° or until golden.]"
2,585,4051,7209,Jazzy,4,"This makes a lovely chocolate chip cookie, but I couldn't taste the Grand Marnier. Perhaps adding a bit of orange zest would enhance the orange flavor.",2001-03-29 17:11:32+00:00,2001-03-29 17:11:32+00:00,Mike's Grand Marnier Chocolate Chip Cookies,1556,...,2.8,10.3,100.6,20.1,1.0,12.4,1.8,NaN,36 cookies,"[Cream margarine, sugars, vanilla and Grand Marnier in a large mixing bowl., Add eggs, beating well after each addition., Add baking soda and flour and stir until blended., Stir in oats, then chocolate chips., Drop by the tablespoonfuls 5 cm apart onto ungreased cookie sheets., Bake at 300°F for 5-10 minutes or until done. Allow to cool somewhat before removing from cookie sheet.]"
3,586,13307,7230,Sadie Schilk,5,"This recipe is awesome! I tried it out of curiosity, brought the cookies to work, and everyone loved them. They fought over who was going to eat the last one. It makes about a million cookies, so unless you are sharing it with a large number of people, cut the recipe in half, or you will have more cookies than you know what to do with!",2001-03-29 17:11:32+00:00,2001-03-29 17:11:32+00:00,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,20914,...,4.5,18.5,127.6,22.8,1.5,13.9,2.5,NaN,96 cookies,"[Measure oatmeal and blend in a blender to a fine powder., Cream the butter and both sugars., Add eggs and vanilla., Mix together with flour, oatmeal, salt, baking powder and soda., Add chocolate chips, grated Hershey Bar and nuts., Roll into 1 inch balls and place 2-inches apart on a cookie sheet., Bake for 10 minutes at 375° or until golden.]"
4,630,3307,7673,Rachel Merrell,1,"dough is too thin, the cookies melted together and they came out really thin. Flavor was ok.",2001-04-04 16:51:30+00:00,2001-04-04 16:51:30+00:00,Mrs. Fields Chocolate Chip Cookies,1763,...,4.3,21.7,66.3,14.9,0.6,11.9,1.0,NaN,42 cookies,"[Heat oven to 300°F., Combine flour, baking soda and salt in medium bowl using whisk; set aside., Mix sugars in bowl with an electric mixer on medium speed., Add butter; beat until grainy paste forms., Beat in eggs and vanilla on medium speed until light and fluffy., Add flour mixture and chocolate chips., Beat on low speed just until mixed., Do not over mix., Drop dough by rounded tablespoons onto ungreased baking sheets, 2-inches apart. Bake for 22 minutes until golden brown., Transfer cookies to cooling rack.]"

In [56]:
classic_cookie_reviews["RecipeIngredientParts"] = (
    classic_cookie_reviews["RecipeIngredientParts"]
    .astype(str)
)

classic_cookie_reviews["RecipeInstructions"] = (
    classic_cookie_reviews["RecipeInstructions"]
    .astype(str)
)

In [57]:
classic_cookie_recipe_level = (
    classic_cookie_reviews
    .groupby(
        [
            "RecipeId",
            "Name",
            "RecipeIngredientParts",
            "RecipeInstructions"
        ]
    )
    .agg(
        num_reviews=("Review", "count"),
        avg_rating=("Rating", "mean"),
        all_reviews=("Review", " ".join)
    )
    .reset_index()
)

In [58]:
classic_cookie_recipe_level.shape

(594, 7)

In [59]:
classic_cookie_recipe_level.head()

   RecipeId                                           Name  \
0      3307             Mrs. Fields Chocolate Chip Cookies
1      3599              Best Basic Chocolate Chip Cookies
2      4050  Canadian Living's Best Chocolate Chip Cookies
3      4051    Mike's Grand Marnier Chocolate Chip Cookies
4      4092                         Chocolate Chip Cookies

                                                                                                                                         RecipeIngredientParts  \
0                                                    ['all-purpose flour' 'baking soda' 'salt' 'dark brown sugar' 'sugar'\n 'butter' 'eggs' 'vanilla extract']
1                      ['shortening' 'butter' 'brown sugar' 'granulated sugar' 'baking soda'\n 'salt' 'eggs' 'vanilla' 'all-purpose flour' 'walnuts' 'pecans']
2  ['butter' 'shortening' 'granulated sugar' 'brown sugar' 'eggs' 'vanilla'\n 'all-purpose flour' 'baking soda' 'salt' 'chocolate chips' 'walnuts'\n 'pecans']
3                             ['margarine' 'brown sugar' 'granulated sugar' 'vanilla' 'Grand Marnier'\n 'eggs' 'all-purpose flour' 'baking soda' 'quick oats']
4                               ['butter' 'caster sugar' 'brown sugar' 'egg' 'vanilla extract'\n 'plain flour' 'salt' 'bicarbonate of soda' 'chocolate chips']

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RecipeInstructions  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ['Heat oven to 300°F.'\n 'Combine flour, baking soda and salt in medium bowl using whisk; set aside.'\n 'Mix sugars in bowl with an electric mixer on medium speed.'\n 'Add butter; beat until grainy paste forms.'\n 'Beat in eggs and vanilla on  medium speed until light and fluffy.'\n 'Add flour mixture and chocolate chips.'\n 'Beat on low speed just until mixed.' 'Do not over mix.'\n 'Drop dough by rounded tablespoons onto ungreased baking sheets, 2-inches apart.  Bake for 22 minutes until golden brown.'\n 'Transfer cookies to cooling rack.']
1  ['Thin-and-Crispy: Bake 10-12 min per batch.'\n '1 cup butter, 3/4 cup packed brown sugar, 3/4 cup granulated sugar, 1/2 tsp baking soda, 1/4 tsp salt, 1 egg, 1 tsp vanilla, 2 cup all-purpose flour, 1 1/2 cups semisweet chocolate pieces, 1 cup chopped walnuts or pecans.'\n 'Soft-and-Cake-like  Bake 9-11 minutes per batch.'\n '1/2 cup shortening, 1 1/2 cup packed brown sugar, 2 slightly beaten eggs, 1 tsp vanilla, 2 1/2 cup all-purpose flour, 1 tsp baking soda, 1/2 tsp baking powder, 1/2 tsp salt, 8 oz sour cream, 1 1/2 cup semisweet chocolate pieces, 1 cup chopped walnuts or pecans.'\n 'Preheat oven to 375°.'\n 'FOR BASIC OR THIN COOKIES:  in a bowl beat shortening and/or butter on medium to high speed for 30 seconds.'\n 'Add brown sugar, granulated sugar, baking soda and salt; beat until combined.'\n 'Beat in egg or eggs and vanilla until combined.'\n 'Beat in as much of the flour as you can with a mixer.'\n 'With a wooden spoon, stir in remaining  flour.'\n 'Notes: If you use the beaters on your electric mixer, you can skip the wooden spoon.)  Stir in chocolate pieces and nuts.'\n 'Drop dough by rounded teaspoons 2-inches apart on an ungreased cookie sheet.  Bake Basic cookies 8-10 minutes, and Thin cookies 10-12 minutes or until edges are browned.'\n 'Cool on wire rack.'\n 'FOR CAKELIKE COOKIES: In a bowl, beat shortening and brown sugar on medium to high speed until combined.'\n 'Add eggs and vanilla; bean until combined.'\n 'Combine flour, baking soda, baking powder and salt.  Alternately add flour mixture and sour cream to shortening mixture, beating after each addition.'\n 'With a wooden spoon, stir in chocolate pieces and nuts.'\n 'Drop by rounded teaspoons 2 inches apart on ungreased cookie sheet.  Bake 9-11 minutes or until edges are browned.'\n 'Cool on wire rack.']
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ['In a large bowl, cream together butter and shortening; gradually mix in sugars, creaming thoroughly.'\n 'Beat in eggs and vanilla.'\n 'Combine flour, baking soda and salt; blend into creamed mixture. Stir in chocolate chips and nuts.'\n 'Chill for a few minutes or let stand at cool room temperature for 30 minutes.'\n 'Drop by rounded teaspoonfuls onto lightly greased baking sheets.'\n 'Flatten slightly and smooth edges to make 1/2-inch thick cookie.'\n 'Bake in a 375°F oven for 8-9 minutes or until golden brown around the edges and still slightly under-baked in the centre. Let stand on baking sheet for 5 minutes; remove to racks to let cool completely.']
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ['Cream margarine, sugars, vanilla and Grand Marnier in a large mixing bowl.'\n 'Add eggs, beating well after each addition.'\n 'Add baking soda and flour and stir until blended.'\n 'Stir in oats, then chocolate chips.'\n 'Drop by the tablespoonfuls 5 cm apart onto ungreased cookie sheets.'\n 'Bake at 300°F for 5-10 minutes or until done. Allow to cool somewhat before removing from cookie sheet.']
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ['Set the oven to 190°C/375°F/Gas 5.'\n 'Beat the butter and sugars together in a mixing bowl until creamy.'\n 'Break the egg into the bowl and beat it into the mixture until smooth.'\n 'Then add the vanilla essence and mix.'\n 'Add the flour, salt and bicarbonate of soda to the mixture, a little at a time, and stir everything together well.'\n 'Now add the chocolate chips and stir them in until they are evenly spread through the mixture.'\n 'Butter the baking trays and spoon small mounds of the mixture on them leaving quite big spaces between the  mounds.'\n 'Bake the cookies for 10 to 12 minutes until they are an even golden  brown colour, then transfer them to a wire rack to cool.']

   num_reviews  avg_rating  \
0            8    2.250000
1           11    4.090909
2           82    4.390244
3            2    4.000000
4            8    4.625000


In [60]:
texture_words = [
    "chewy",
    "chewier",
    "crispy",
    "crisp",
    "crunchy",
    "soft",
    "gooey",
    "cakey",
    "cake-like",
    "thick",
    "thin",
    "flat",
    "spread",
    "spreading",
    "dry",
    "moist",
    "dense"
]

In [61]:
for word in texture_words:
    review_mentions = (
        classic_cookie_recipe_level["all_reviews"]
        .str.lower()
        .str.count(word)
        .sum()
    )
    
    recipe_mentions = (
        classic_cookie_recipe_level["all_reviews"]
        .str.lower()
        .str.contains(word)
        .sum()
    )
    
    print(f"{word:10} reviews={review_mentions:5.0f} | recipes={recipe_mentions}")

chewy      reviews=  918 | recipes=215
chewier    reviews=   23 | recipes=16
crispy     reviews=  248 | recipes=113
crisp      reviews=  454 | recipes=169
crunchy    reviews=  153 | recipes=64
soft       reviews= 1033 | recipes=218
gooey      reviews=   79 | recipes=39
cakey      reviews=   73 | recipes=38
cake-like  reviews=   26 | recipes=19
thick      reviews=  208 | recipes=66
thin       reviews= 1301 | recipes=270
flat       reviews=  440 | recipes=138
spread     reviews=  237 | recipes=101
spreading  reviews=   22 | recipes=20
dry        reviews=  201 | recipes=75
moist      reviews=  175 | recipes=74
dense      reviews=   28 | recipes=18

In [62]:
for word in texture_words:
    column_name = word.replace("-", "_")
    
    classic_cookie_recipe_level[column_name] = (
        classic_cookie_recipe_level["all_reviews"]
        .str.lower()
        .str.contains(word)
        .astype(int)
    )

In [63]:
classic_cookie_recipe_level[
    [
        "Name",
        "soft",
        "chewy",
        "thin",
        "crispy",
        "thick"
    ]
].head(20)

,Name,soft,chewy,thin,crispy,thick
0,Mrs. Fields Chocolate Chip Cookies,0,0,1,0,0
1,Best Basic Chocolate Chip Cookies,1,0,1,0,0
2,Canadian Living's Best Chocolate Chip Cookies,1,1,1,1,1
3,Mike's Grand Marnier Chocolate Chip Cookies,1,0,0,0,0
4,Chocolate Chip Cookies,1,0,1,0,0
5,Decadent Chocolate Chip Cookies,1,1,1,1,1
6,Crispy Chewy Chocolate Chip Cookies,1,1,1,1,0
7,Best Ever Chocolate Chip Cookies,1,1,1,1,0
8,Soft Batch Chocolate Chip Cookies,1,1,1,1,1
9,The Ultimate Chocolate Chip Cookies!,0,1,0,1,1
10,Chocolate Chip Cookies,1,1,1,0,0
11,Chocolate Chip Cookies (Grandma's From-Scratch - It's Easy!),0,1,1,0,0
12,Neiman-Marcus $250 Chocolate Chip Cookies Recipe,1,1,1,1,1
13,Ghirardelli' S Ultimate Chocolate Chip Cookies,1,1,1,1,0
14,Rich chocolate chip cookies,0,0,0,0,0
15,Decadent Chocolate Chip Cookies for Kisses,0,0,1,0,0
16,Easy chocolate chip cookies,1,0,1,0,0
17,Chewy Chocolate Chip Cookies,0,0,0,0,0
18,Chewy Delicious Chocolate Chip Cookies,1,1,1,1,1
19,Slice &amp; Bake Chocolate Chip Cookies,0,1,0,1,0

In [66]:
classic_cookie_recipe_level.to_csv(
    "classic_cookie_texture_dataset.csv",
    index=False
)

In [67]:
print(classic_cookie_recipe_level)

     RecipeId                                           Name  \
0        3307             Mrs. Fields Chocolate Chip Cookies
1        3599              Best Basic Chocolate Chip Cookies
2        4050  Canadian Living's Best Chocolate Chip Cookies
3        4051    Mike's Grand Marnier Chocolate Chip Cookies
4        4092                         Chocolate Chip Cookies
..        ...                                            ...
589    522478         BEST-EVER Chewy Chocolate Chip Cookies
590    522705                         Chocolate Chip Cookies
591    530178            Paleo Almond Chocolate Chip Cookies
592    530828                         Chocolate Chip Cookies
593    533923          Ultimate Chewy Chocolate Chip Cookies

                                                                                                                                                    RecipeIngredientParts  \
0                                                               ['all-purpose flour' 'baking soda' 'salt' 'dark brown sugar' 'sugar'\n 'butter' 'eggs' 'vanilla extract']
1                                 ['shortening' 'butter' 'brown sugar' 'granulated sugar' 'baking soda'\n 'salt' 'eggs' 'vanilla' 'all-purpose flour' 'walnuts' 'pecans']
2             ['butter' 'shortening' 'granulated sugar' 'brown sugar' 'eggs' 'vanilla'\n 'all-purpose flour' 'baking soda' 'salt' 'chocolate chips' 'walnuts'\n 'pecans']
3                                        ['margarine' 'brown sugar' 'granulated sugar' 'vanilla' 'Grand Marnier'\n 'eggs' 'all-purpose flour' 'baking soda' 'quick oats']
4                                          ['butter' 'caster sugar' 'brown sugar' 'egg' 'vanilla extract'\n 'plain flour' 'salt' 'bicarbonate of soda' 'chocolate chips']
..                                                                                                                                                                    ...
589  ['unsalted butter' 'brown sugar' 'granulated sugar' 'egg'\n 'vanilla extract' 'all-purpose flour' 'cornstarch' 'baking soda' 'salt'\n 'bittersweet chocolate chips']
590                                                 ['shortening' 'butter' 'vanilla' 'eggs' 'sugar' 'light brown sugar'\n 'flour' 'baking soda' 'salt' 'chocolate chips']
591                                                                                      ['baking soda' 'sea salt' 'coconut oil' 'maple syrup' 'egg'\n 'vanilla extract']
592                                                                  ['shortening' 'white sugar' 'brown sugar' 'vanilla' 'eggs' 'flour'\n 'baking soda' 'salt' 'walnuts']
593              ['all-purpose flour' 'kosher salt' 'baking soda' 'unsalted butter'\n 'light brown sugar' 'granulated sugar' 'eggs' 'vanilla extract'\n 'dark chocolate']

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  RecipeInstructions  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ['Heat oven to 300°F.'\n 'Combine flour, baking soda and salt in medium bowl using whisk; set aside.'\n 'Mix sugars in bowl with an electric mixer on medium speed.'\n 'Add butter; beat until grainy paste forms.'\n 'Beat in eggs and vanilla on  medium speed until light and fluffy.'\n 'Add flour mixture and chocolate chips.'\n 'Beat on low speed just until mixed.' 'Do not over mix.'\n 'Drop dough by rounded tablespoons onto ungreased baking sheets, 2-inches apart.  Bake for 22 minutes until golden brown.'\n 'Transfer cookies to cooling rack.']
1    ['Thin-and-Crispy: Bake 10-12 min per batch.'\n '1 cup butter, 3/4 cup packed brown sugar, 3/4 cup granulated sugar, 1/2 tsp baking soda, 1/4 tsp salt, 1 egg, 1 tsp vanilla, 2 cup all-purpose flour, 1 1/2 cups semisweet chocolate pieces, 1 cup chopped walnuts or pecans.'\n 'Soft-and-Cake-like  Bake 9-11 minutes per batch.'\n '1/2 cup shortening, 1 1/2 cup packed brown sugar, 2 slightly beaten eggs, 1 tsp vanilla, 2 1/2 cup all-purpose flour, 1 tsp baking soda, 1/2 tsp baking powder, 1/2 tsp salt, 8 oz sour cream, 1 1/2 cup semisweet chocolate pieces, 1 cup chopped walnuts or pecans.'\n 'Preheat oven to 375°.'\n 'FOR BASIC OR THIN COOKIES:  in a bowl beat shortening and/or butter on medium to high speed for 30 seconds.'\n 'Add brown sugar, granulated sugar, baking soda and salt; beat until combined.'\n 'Beat in egg or eggs and vanilla until combined.'\n 'Beat in as much of the flour as you can with a mixer.'\n 'With a wooden spoon, stir in remaining  flour.'\n 'Notes: If you use the beaters on your electric mixer, you can skip the wooden spoon.)  Stir in chocolate pieces and nuts.'\n 'Drop dough by rounded teaspoons 2-inches apart on an ungreased cookie sheet.  Bake Basic cookies 8-10 minutes, and Thin cookies 10-12 minutes or until edges are browned.'\n 'Cool on wire rack.'\n 'FOR CAKELIKE COOKIES: In a bowl, beat shortening and brown sugar on medium to high speed until combined.'\n 'Add eggs and vanilla; bean until combined.'\n 'Combine flour, baking soda, baking powder and salt.  Alternately add flour mixture and sour cream to shortening mixture, beating after each addition.'\n 'With a wooden spoon, stir in chocolate pieces and nuts.'\n 'Drop by rounded teaspoons 2 inches apart on ungreased cookie sheet.  Bake 9-11 minutes or until edges are browned.'\n 'Cool on wire rack.']
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ['In a large bowl, cream together butter and shortening; gradually mix in sugars, creaming thoroughly.'\n 'Beat in eggs and vanilla.'\n 'Combine flour, baking soda and salt; blend into creamed mixture. Stir in chocolate chips and nuts.'\n 'Chill for a few minutes or let stand at cool room temperature for 30 minutes.'\n 'Drop by rounded teaspoonfuls onto lightly greased baking sheets.'\n 'Flatten slightly and smooth edges to make 1/2-inch thick cookie.'\n 'Bake in a 375°F oven for 8-9 minutes or until golden brown around the edges and still slightly under-baked in the centre. Let stand on baking sheet for 5 minutes; remove to racks to let cool completely.']
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ['Cream margarine, sugars, vanilla and Grand Marnier in a large mixing bowl.'\n 'Add eggs, beating well after each addition.'\n 'Add baking soda and flour and stir until blended.'\n 'Stir in oats, then chocolate chips.'\n 'Drop by the tablespoonfuls 5 cm apart onto ungreased cookie sheets.'\n 'Bake at 300°F for 5-10 minutes or until done. Allow to cool somewhat before removing from cookie sheet.']
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ['Set the oven to 190°C/375°F/Gas 5.'\n 'Beat the butter and sugars together in a mixing bowl until creamy.'\n 'Break the egg into the bowl and beat it into the mixture until smooth.'\n 'Then add the vanilla essence and mix.'\n 'Add the flour, salt and bicarbonate of soda to the mixture, a little at a time, and stir everything together well.'\n 'Now add the chocolate chips and stir them in until they are evenly spread through the mixture.'\n 'Butter the baking trays and spoon small mounds of the mixture on them leaving quite big spaces between the  mounds.'\n 'Bake the cookies for 10 to 12 minutes until they are an even golden  brown colour, then transfer them to a wire rack to cool.']
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ...
589                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ['1.  Preheat oven to 350 degrees F.'\n '2.  In the bowl of a stand mixer fitted with a paddle attachment, cream together butter and sugars until fluffy and light in color. Add egg and vanilla and blend inches.'\n '3.  Mix in flour, cornstarch, baking soda and salt. Stir in chocolate chunks.'\n '4.  Using a standard-sized cookie scoop or tablespoon, drop dough onto a prepared baking sheet.  Bake for 8-10 minutes, until barely golden brown around the edges.  (The tops will not brown, but do NOT cook longer than ten minutes.).'\n '5.  Let cool, on the sheet, on a wire rack for five minutes.  Remove from baking sheet and let cool completely.  Makes approximately 3 dozen.  Try not to eat them all.']
590                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ["Mix the shortening with the butter in your mixer. Don't mix it too well, you don't want a perfectly consistent texture."\n 'Add the 2 sugars and mix.' 'Add the eggs and vanilla and mix.'\n 'Add 2 cups of the flour, retaining the other cup to mix the salt and baking soda.'\n 'Add the last cup of flour, mix well.'\n 'Add the chocolate chips, mix well.'\n 'Drop by  heaping tablespoon onto a cookie sheet.'\n 'Bake in a preheated 375 degree oven for 7.5 to 8.5 minutes. They are done when the tops have light brown tips on the peaks.'\n 'Remove from the oven and let them sit on the baking sheet for five minutes, remove and place on wax paper that is sitting on your counter, or a cooling rack.']

# Classic Chocolate Chip Cookie Dataset Cleaning

## Objective

The goal of this project is to create a machine learning dataset that can predict chocolate chip cookie texture (such as soft, chewy, thin, or crispy) based on recipe characteristics including ingredients and instructions.

To create this dataset, the original recipe database was filtered to isolate classic chocolate chip cookie recipes and then combined with user reviews to generate texture labels.

---

# 1. Initial Dataset

The original dataset contained:

- **522,517 recipes**
- **1,401,982 reviews**

Each recipe contained information including:

- Recipe ID
- Recipe name
- Recipe category
- Ingredients
- Instructions
- Author information
- Recipe metadata

---

# 2. Identify Chocolate Chip Cookie Candidates

Recipes were first filtered based on recipe names containing chocolate chip cookie-related terms.

This created:

`choc_chip_candidates`

**1,775 recipes**

This dataset contained both true chocolate chip cookie recipes and unrelated recipes that included the phrase "chocolate chip cookie."

Examples of unrelated recipes included:

- Chocolate Chip Cookie Pie
- Chocolate Chip Cookie Ice Cream Cake
- Chocolate Chip Cookie Cheesecake
- Chocolate Chip Cookie Milkshake

---

# 3. Remove Non-Cookie Recipes

The candidate dataset was cleaned to remove recipes that were not traditional chocolate chip cookies.

Recipes were removed based on:

- Recipe categories
- Recipe names
- Keywords indicating non-cookie desserts

Examples of removed categories:

- Bar Cookie
- Pie
- Frozen Desserts
- Cheesecake
- Ice Cream
- Beverages
- Cakes
- Sandwiches
- Cookie Mixes

After removing unrelated recipes:

`classic_candidates`

**1,258 recipes**

---

# 4. Refine Classic Chocolate Chip Cookie Recipes

Additional cleaning was performed to create a more representative classic chocolate chip cookie dataset.

This produced:

`classic_cookies_clean`

**1,205 recipes**

Duplicate recipe names were then investigated.

A total of:

**421 duplicate recipe names**

were identified.

Duplicates were reviewed because identical recipe names could represent different recipes from different authors.

After duplicate analysis, the final cleaned recipe dataset was:

`classic_cookies_final`

**1,180 recipes**

This dataset contains:

- Recipe ID
- Recipe name
- Recipe category
- Ingredients
- Instructions
- Author information
- Recipe metadata

---

# 5. Merge Recipes With Reviews

The cleaned recipe dataset was merged with the review dataset using:

`RecipeId`

An inner join was used so that only recipes with available reviews were retained.

The resulting dataset:

`classic_cookie_reviews`

contained:

**5,515 review rows**

Each row represented:

- One review
- The associated cookie recipe
- Recipe information

---

# 6. Convert Review-Level Data Into Recipe-Level Data

Because each recipe could have many reviews, the review-level dataset was converted into a recipe-level dataset.

Reviews were grouped by recipe and combined.

For each recipe:

- All reviews were combined into one text field
- The number of reviews was calculated
- The average rating was calculated

The final recipe-level dataset:

`classic_cookie_recipe_level`

contained:

**594 recipes**

Each row represents one cookie recipe.

Schema:

| Column | Description |
|---|---|
| RecipeId | Unique recipe identifier |
| Name | Recipe name |
| RecipeIngredientParts | List of recipe ingredients |
| RecipeInstructions | Baking instructions |
| num_reviews | Number of reviews associated with the recipe |
| avg_rating | Average review rating |
| all_reviews | All reviews combined into one text field |

---

# 7. Final Dataset Purpose

The final dataset will be used to predict cookie texture.

The recipe information will serve as model inputs:

- Ingredients
- Instructions
- Recipe characteristics

The combined reviews will be used to generate texture labels.

Example:

Reviews:

> "These cookies are soft, chewy, and stay thick."

Converted into labels:

| Texture | Label |
|---|---|
| Soft | 1 |
| Chewy | 1 |
| Thick | 1 |
| Crispy | 0 |

These labels will become the prediction targets for machine learning models.

---

# Dataset Pipeline Summary

```
Raw Recipe Dataset
        |
        ↓
Chocolate Chip Cookie Candidates
(1,775 recipes)
        |
        ↓
Remove Non-Cookie Recipes
        |
        ↓
Classic Cookie Recipes
(1,258 recipes)
        |
        ↓
Clean + Remove Duplicates
        |
        ↓
classic_cookies_final
(1,180 recipes)
        |
        ↓
Merge With Reviews
        |
        ↓
classic_cookie_reviews
(5,515 reviews)
        |
        ↓
Aggregate Reviews by Recipe
        |
        ↓
classic_cookie_recipe_level
(594 recipes)
```

---

# Completed Steps

✅ Loaded recipe and review datasets  
✅ Identified chocolate chip cookie recipes  
✅ Removed unrelated desserts  
✅ Cleaned classic cookie recipes  
✅ Investigated duplicate recipes  
✅ Created final recipe dataset  
✅ Merged recipes with reviews  
✅ Aggregated reviews into recipe-level data  
✅ Prepared dataset for texture label generation and machine learning  

---

# Next Steps

The next notebook will focus on:

1. Exploratory texture analysis
2. Extracting texture labels from reviews:
   - Soft
   - Chewy
   - Thin
   - Crispy
   - Thick
   - Gooey
   - Cakey

3. Feature engineering:
   - Ingredient analysis
   - Recipe instruction analysis

4. Machine learning models to predict cookie texture